/**
 * Parts domain contract tests — Phase 0 golden file
 *
 * This file captures the response shapes for the legacy parts-related routes that
 * the unified parts catalog (ADR 0010, docs/plans/2026-04-10-parts-catalog-consolidation.md)
 * replaces. Each test asserts the canonical envelope + the fields downstream code
 * depends on. These tests MUST remain green through Phases 1-5 unchanged — they are
 * the regression gate that proves the legacy API surface is unchanged during dual-write.
 *
 * Phase 6 hard-deletes the legacy routes; this file can be deleted in the same commit.
 *
 * DO NOT edit this file to fix a failing test. If it fails, something in the parts
 * refactor broke consumer-visible contracts — fix the code, not the test.
 */

import { describe, it, expect, beforeEach, vi } from 'vitest';
import express, { type Express } from 'express';
import { registerBomRoutes } from '../../routes/bom';
import { registerComponentRoutes } from '../../routes/components';

// ---------------------------------------------------------------------------
// Mock storage
// ---------------------------------------------------------------------------

const {
  mockGetBomItems,
  mockGetBomItem,
  mockGetComponentParts,
  mockGetLibraryEntries,
  mockGetLibraryEntry,
  mockGetProject,
} = vi.hoisted(() => ({
  mockGetBomItems: vi.fn(),
  mockGetBomItem: vi.fn(),
  mockGetComponentParts: vi.fn(),
  mockGetLibraryEntries: vi.fn(),
  mockGetLibraryEntry: vi.fn(),
  mockGetProject: vi.fn(),
}));

vi.mock('../../storage', () => ({
  storage: {
    getProject: mockGetProject,
    getBomItems: mockGetBomItems,
    getBomItem: mockGetBomItem,
    getLowStockItems: vi.fn().mockResolvedValue([]),
    getStorageLocations: vi.fn().mockResolvedValue([]),
    getComponentParts: mockGetComponentParts,
    getLibraryEntries: mockGetLibraryEntries,
    getLibraryEntry: mockGetLibraryEntry,
  },
  VersionConflictError: class VersionConflictError extends Error {
    currentVersion: number;
    constructor(entity: string, id: number, currentVersion: number) {
      super('Version conflict');
      this.name = 'VersionConflictError';
      this.currentVersion = currentVersion;
    }
  },
}));

vi.mock('../../auth', () => ({
  validateSession: vi.fn().mockResolvedValue({ userId: 1, sessionId: 'test-session' }),
  getApiKey: vi.fn().mockResolvedValue(null),
}));

vi.mock('../../routes/auth-middleware', () => ({
  requireProjectOwnership: (_req: unknown, _res: unknown, next: () => void) => next(),
}));

vi.mock('../../db', () => ({ db: {}, pool: {}, checkConnection: vi.fn() }));

vi.mock('../../logger', () => ({
  logger: { info: vi.fn(), warn: vi.fn(), error: vi.fn(), debug: vi.fn() },
}));

// ---------------------------------------------------------------------------
// Test app + fixtures
// ---------------------------------------------------------------------------

function makeApp(): Express {
  const app = express();
  app.use(express.json());
  registerBomRoutes(app);
  registerComponentRoutes(app);
  return app;
}

async function listen(app: Express): Promise<{ url: string; close: () => void }> {
  return new Promise((resolve) => {
    const server = app.listen(0, () => {
      const address = server.address();
      const port = typeof address === 'object' && address ? address.port : 0;
      resolve({
        url: `http://127.0.0.1:${port}`,
        close: () => server.close(),
      });
    });
  });
}

const NOW = new Date('2026-04-11T12:00:00Z');

const SAMPLE_BOM_ITEM = {
  id: 1,
  projectId: 10,
  partNumber: 'R-10K-0402-1%',
  manufacturer: 'Yageo',
  description: '10 kΩ 0402 1%',
  quantity: 5,
  unitPrice: '0.0023',
  totalPrice: '0.0115',
  supplier: 'LCSC',
  stock: 5000,
  status: 'In Stock',
  leadTime: '1 week',
  datasheetUrl: null,
  manufacturerUrl: null,
  storageLocation: 'Bin A3',
  quantityOnHand: 50,
  minimumStock: 10,
  esdSensitive: false,
  assemblyCategory: 'smt',
  tolerance: '1%',
  version: 1,
  createdAt: NOW,
  updatedAt: NOW,
  deletedAt: null,
} as const;

const SAMPLE_COMPONENT_PART = {
  id: 1,
  projectId: 10,
  nodeId: 'node-abc',
  meta: { title: '10kΩ Resistor', category: 'passive' },
  connectors: [],
  buses: [],
  views: {},
  constraints: [],
  version: 1,
  createdAt: NOW,
  updatedAt: NOW,
} as const;

const SAMPLE_LIBRARY_ENTRY = {
  id: 1,
  title: '10kΩ Resistor',
  description: 'Standard 10kΩ 0402',
  meta: { category: 'passive' },
  connectors: [],
  buses: [],
  views: {},
  constraints: [],
  tags: ['resistor', 'passive'],
  category: 'passive',
  isPublic: true,
  authorId: null,
  forkedFromId: null,
  downloadCount: 0,
  createdAt: NOW,
  updatedAt: NOW,
} as const;

// ---------------------------------------------------------------------------
// Contract assertions
// ---------------------------------------------------------------------------

describe('Parts domain contract (Phase 0 golden file)', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockGetProject.mockResolvedValue({ id: 10, ownerId: '1' });
  });

  describe('GET /api/projects/:id/bom', () => {
    it('returns { data: BomItem[], total: number } envelope', async () => {
      mockGetBomItems.mockResolvedValue([SAMPLE_BOM_ITEM]);
      const app = makeApp();
      const { url, close } = await listen(app);
      try {
        const res = await fetch(`${url}/api/projects/10/bom`, {
          headers: { 'X-Session-Id': 'test-session' },
        });
        expect(res.status).toBe(200);
        const body = await res.json();
        expect(body).toHaveProperty('data');
        expect(body).toHaveProperty('total');
        expect(Array.isArray(body.data)).toBe(true);
        expect(typeof body.total).toBe('number');
      } finally {
        close();
      }
    });

    it('BOM item rows expose the fields downstream consumers depend on', async () => {
      mockGetBomItems.mockResolvedValue([SAMPLE_BOM_ITEM]);
      const app = makeApp();
      const { url, close } = await listen(app);
      try {
        const res = await fetch(`${url}/api/projects/10/bom`, {
          headers: { 'X-Session-Id': 'test-session' },
        });
        const body = await res.json();
        const row = body.data[0];
        const requiredFields = [
          'id',
          'projectId',
          'partNumber',
          'manufacturer',
          'description',
          'quantity',
          'unitPrice',
          'totalPrice',
          'supplier',
          'status',
          'storageLocation',
          'quantityOnHand',
          'minimumStock',
          'esdSensitive',
          'assemblyCategory',
          'tolerance',
          'version',
        ];
        for (const field of requiredFields) {
          expect(row).toHaveProperty(field);
        }
      } finally {
        close();
      }
    });
  });

  describe('GET /api/projects/:id/bom/:bomId', () => {
    it('returns a single BomItem with the same shape as the list row', async () => {
      mockGetBomItem.mockResolvedValue(SAMPLE_BOM_ITEM);
      const app = makeApp();
      const { url, close } = await listen(app);
      try {
        const res = await fetch(`${url}/api/projects/10/bom/1`, {
          headers: { 'X-Session-Id': 'test-session' },
        });
        expect(res.status).toBe(200);
        const body = await res.json();
        expect(body).toHaveProperty('id', 1);
        expect(body).toHaveProperty('partNumber');
      } finally {
        close();
      }
    });

    it('returns 404 with { message } for unknown id', async () => {
      mockGetBomItem.mockResolvedValue(null);
      const app = makeApp();
      const { url, close } = await listen(app);
      try {
        const res = await fetch(`${url}/api/projects/10/bom/999`, {
          headers: { 'X-Session-Id': 'test-session' },
        });
        expect(res.status).toBe(404);
        const body = await res.json();
        expect(body).toHaveProperty('message');
      } finally {
        close();
      }
    });
  });

  describe('GET /api/projects/:projectId/component-parts', () => {
    it('returns { data: ComponentPart[], total: number } envelope', async () => {
      mockGetComponentParts.mockResolvedValue([SAMPLE_COMPONENT_PART]);
      const app = makeApp();
      const { url, close } = await listen(app);
      try {
        const res = await fetch(`${url}/api/projects/10/component-parts`, {
          headers: { 'X-Session-Id': 'test-session' },
        });
        expect(res.status).toBe(200);
        const body = await res.json();
        expect(body).toHaveProperty('data');
        expect(body).toHaveProperty('total');
        expect(Array.isArray(body.data)).toBe(true);
        const row = body.data[0];
        const requiredFields = ['id', 'projectId', 'nodeId', 'meta', 'connectors', 'buses', 'views', 'constraints', 'version'];
        for (const field of requiredFields) {
          expect(row).toHaveProperty(field);
        }
      } finally {
        close();
      }
    });
  });

  describe('GET /api/component-library', () => {
    it('returns a paginated envelope with library entries', async () => {
      mockGetLibraryEntries.mockResolvedValue({
        data: [SAMPLE_LIBRARY_ENTRY],
        total: 1,
        page: 1,
        limit: 20,
      });
      const app = makeApp();
      const { url, close } = await listen(app);
      try {
        const res = await fetch(`${url}/api/component-library`);
        expect(res.status).toBe(200);
        const body = await res.json();
        expect(body).toHaveProperty('data');
        expect(Array.isArray(body.data)).toBe(true);
        const row = body.data[0];
        const requiredFields = ['id', 'title', 'description', 'meta', 'connectors', 'buses', 'views', 'constraints', 'tags', 'category', 'isPublic'];
        for (const field of requiredFields) {
          expect(row).toHaveProperty(field);
        }
      } finally {
        close();
      }
    });
  });

  describe('GET /api/component-library/:id', () => {
    it('returns a single library entry', async () => {
      mockGetLibraryEntry.mockResolvedValue(SAMPLE_LIBRARY_ENTRY);
      const app = makeApp();
      const { url, close } = await listen(app);
      try {
        const res = await fetch(`${url}/api/component-library/1`);
        expect(res.status).toBe(200);
        const body = await res.json();
        expect(body).toHaveProperty('id', 1);
        expect(body).toHaveProperty('title');
        expect(body).toHaveProperty('meta');
      } finally {
        close();
      }
    });

    it('returns 404 with { message } for unknown id', async () => {
      mockGetLibraryEntry.mockResolvedValue(null);
      const app = makeApp();
      const { url, close } = await listen(app);
      try {
        const res = await fetch(`${url}/api/component-library/999`);
        expect(res.status).toBe(404);
        const body = await res.json();
        expect(body).toHaveProperty('message');
      } finally {
        close();
      }
    });
  });
});
