/**
 * 2xxx — Validation & Input error catalog entries.
 */

import { ErrorCode } from './error-codes';
import { ErrorSeverity } from './error-types';
import type { ErrorCatalogEntry } from './error-types';

export const validationCatalog: Partial<Record<ErrorCode, ErrorCatalogEntry>> = {
  [ErrorCode.VALIDATION_FAILED]: {
    code: ErrorCode.VALIDATION_FAILED,
    httpStatus: 400,
    severity: ErrorSeverity.ERROR,
    label: 'Validation failed',
    description: 'Request body or query parameters did not pass validation.',
    retryable: false,
  },
  [ErrorCode.VALIDATION_FIELD_MISSING]: {
    code: ErrorCode.VALIDATION_FIELD_MISSING,
    httpStatus: 400,
    severity: ErrorSeverity.ERROR,
    label: 'Required field missing',
    description: 'A required field was not included in the request.',
    retryable: false,
  },
  [ErrorCode.VALIDATION_FIELD_RANGE]: {
    code: ErrorCode.VALIDATION_FIELD_RANGE,
    httpStatus: 400,
    severity: ErrorSeverity.ERROR,
    label: 'Field out of range',
    description: 'A field value is outside its allowed minimum/maximum bounds.',
    retryable: false,
  },
  [ErrorCode.VALIDATION_FIELD_FORMAT]: {
    code: ErrorCode.VALIDATION_FIELD_FORMAT,
    httpStatus: 400,
    severity: ErrorSeverity.ERROR,
    label: 'Invalid field format',
    description: 'A field value does not match the expected format or pattern.',
    retryable: false,
  },
  [ErrorCode.VALIDATION_INVALID_ID]: {
    code: ErrorCode.VALIDATION_INVALID_ID,
    httpStatus: 400,
    severity: ErrorSeverity.ERROR,
    label: 'Invalid ID',
    description: 'An ID parameter is not a valid finite number.',
    retryable: false,
  },
  [ErrorCode.VALIDATION_PAGINATION]: {
    code: ErrorCode.VALIDATION_PAGINATION,
    httpStatus: 400,
    severity: ErrorSeverity.ERROR,
    label: 'Invalid pagination',
    description: 'Limit or offset parameters are out of allowed range.',
    retryable: false,
  },
  [ErrorCode.VALIDATION_PAYLOAD_TOO_LARGE]: {
    code: ErrorCode.VALIDATION_PAYLOAD_TOO_LARGE,
    httpStatus: 413,
    severity: ErrorSeverity.ERROR,
    label: 'Payload too large',
    description: 'The request body exceeds the maximum allowed size.',
    retryable: false,
  },
  [ErrorCode.VALIDATION_JSON_PARSE]: {
    code: ErrorCode.VALIDATION_JSON_PARSE,
    httpStatus: 400,
    severity: ErrorSeverity.ERROR,
    label: 'Malformed JSON',
    description: 'The request body is not valid JSON.',
    retryable: false,
  },
  [ErrorCode.VALIDATION_SCHEMA]: {
    code: ErrorCode.VALIDATION_SCHEMA,
    httpStatus: 400,
    severity: ErrorSeverity.ERROR,
    label: 'Schema validation error',
    description: 'Zod schema validation failed. See details for specific field errors.',
    retryable: false,
  },
  [ErrorCode.VALIDATION_DRC_VIOLATION]: {
    code: ErrorCode.VALIDATION_DRC_VIOLATION,
    httpStatus: 422,
    severity: ErrorSeverity.WARNING,
    label: 'DRC violation',
    description: 'Design Rule Check detected violations in the design.',
    retryable: false,
  },
  [ErrorCode.VALIDATION_ERC_VIOLATION]: {
    code: ErrorCode.VALIDATION_ERC_VIOLATION,
    httpStatus: 422,
    severity: ErrorSeverity.WARNING,
    label: 'ERC violation',
    description: 'Electrical Rule Check detected violations in the circuit.',
    retryable: false,
  },
  [ErrorCode.VALIDATION_DFM_FAILED]: {
    code: ErrorCode.VALIDATION_DFM_FAILED,
    httpStatus: 422,
    severity: ErrorSeverity.WARNING,
    label: 'DFM check failed',
    description: 'Design for Manufacturing check found manufacturability issues.',
    retryable: false,
  },
  [ErrorCode.VALIDATION_NET_CLASS]: {
    code: ErrorCode.VALIDATION_NET_CLASS,
    httpStatus: 422,
    severity: ErrorSeverity.WARNING,
    label: 'Net class constraint violated',
    description: 'A net class rule (trace width, clearance, etc.) was violated.',
    retryable: false,
  },
  [ErrorCode.VALIDATION_PLACEMENT]: {
    code: ErrorCode.VALIDATION_PLACEMENT,
    httpStatus: 422,
    severity: ErrorSeverity.WARNING,
    label: 'Placement constraint violated',
    description: 'Component placement overlaps or violates courtyard/keepout rules.',
    retryable: false,
  },
  [ErrorCode.VALIDATION_EXPRESSION_SYNTAX]: {
    code: ErrorCode.VALIDATION_EXPRESSION_SYNTAX,
    httpStatus: 400,
    severity: ErrorSeverity.ERROR,
    label: 'Expression syntax error',
    description: 'A design variable expression has invalid syntax.',
    retryable: false,
  },
  [ErrorCode.VALIDATION_CIRCULAR_DEPENDENCY]: {
    code: ErrorCode.VALIDATION_CIRCULAR_DEPENDENCY,
    httpStatus: 400,
    severity: ErrorSeverity.ERROR,
    label: 'Circular dependency',
    description: 'Design variables form a circular dependency cycle.',
    retryable: false,
  },
  [ErrorCode.VALIDATION_DIVISION_BY_ZERO]: {
    code: ErrorCode.VALIDATION_DIVISION_BY_ZERO,
    httpStatus: 400,
    severity: ErrorSeverity.ERROR,
    label: 'Division by zero',
    description: 'A design variable expression attempted division by zero.',
    retryable: false,
  },
  [ErrorCode.VALIDATION_UNDEFINED_VARIABLE]: {
    code: ErrorCode.VALIDATION_UNDEFINED_VARIABLE,
    httpStatus: 400,
    severity: ErrorSeverity.ERROR,
    label: 'Undefined variable',
    description: 'An expression references a variable that has not been defined.',
    retryable: false,
  },
  [ErrorCode.VALIDATION_URL]: {
    code: ErrorCode.VALIDATION_URL,
    httpStatus: 400,
    severity: ErrorSeverity.ERROR,
    label: 'Invalid URL',
    description: 'The URL is malformed or uses a disallowed protocol.',
    retryable: false,
  },
  [ErrorCode.VALIDATION_SVG_UNSAFE]: {
    code: ErrorCode.VALIDATION_SVG_UNSAFE,
    httpStatus: 400,
    severity: ErrorSeverity.ERROR,
    label: 'Unsafe SVG content',
    description: 'SVG content contains script, event handlers, or other unsafe elements.',
    retryable: false,
  },
};
