/**
 * 5xxx — Circuit & Simulation error catalog entries.
 */

import { ErrorCode } from './error-codes';
import { ErrorSeverity } from './error-types';
import type { ErrorCatalogEntry } from './error-types';

export const circuitCatalog: Partial<Record<ErrorCode, ErrorCatalogEntry>> = {
  [ErrorCode.CIRCUIT_ERROR]: {
    code: ErrorCode.CIRCUIT_ERROR,
    httpStatus: 500,
    severity: ErrorSeverity.ERROR,
    label: 'Circuit error',
    description: 'A generic circuit operation failed.',
    retryable: true,
  },
  [ErrorCode.CIRCUIT_NOT_FOUND]: {
    code: ErrorCode.CIRCUIT_NOT_FOUND,
    httpStatus: 404,
    severity: ErrorSeverity.ERROR,
    label: 'Circuit design not found',
    description: 'The specified circuit design does not exist.',
    retryable: false,
  },
  [ErrorCode.CIRCUIT_INSTANCE_NOT_FOUND]: {
    code: ErrorCode.CIRCUIT_INSTANCE_NOT_FOUND,
    httpStatus: 404,
    severity: ErrorSeverity.ERROR,
    label: 'Component instance not found',
    description: 'The specified component instance does not exist in the circuit.',
    retryable: false,
  },
  [ErrorCode.CIRCUIT_WIRE_NOT_FOUND]: {
    code: ErrorCode.CIRCUIT_WIRE_NOT_FOUND,
    httpStatus: 404,
    severity: ErrorSeverity.ERROR,
    label: 'Wire not found',
    description: 'The specified wire does not exist in the circuit.',
    retryable: false,
  },
  [ErrorCode.CIRCUIT_NET_NOT_FOUND]: {
    code: ErrorCode.CIRCUIT_NET_NOT_FOUND,
    httpStatus: 404,
    severity: ErrorSeverity.ERROR,
    label: 'Net not found',
    description: 'The specified net does not exist in the circuit.',
    retryable: false,
  },
  [ErrorCode.CIRCUIT_AUTOROUTE_FAILED]: {
    code: ErrorCode.CIRCUIT_AUTOROUTE_FAILED,
    httpStatus: 422,
    severity: ErrorSeverity.WARNING,
    label: 'Autoroute failed',
    description: 'The autorouter could not complete routing for all nets.',
    retryable: true,
  },
  [ErrorCode.CIRCUIT_PUSH_SHOVE_FAILED]: {
    code: ErrorCode.CIRCUIT_PUSH_SHOVE_FAILED,
    httpStatus: 422,
    severity: ErrorSeverity.WARNING,
    label: 'Push-and-shove failed',
    description: 'Push-and-shove routing could not resolve trace conflicts.',
    retryable: true,
  },
  [ErrorCode.CIRCUIT_DIFF_PAIR_ERROR]: {
    code: ErrorCode.CIRCUIT_DIFF_PAIR_ERROR,
    httpStatus: 422,
    severity: ErrorSeverity.WARNING,
    label: 'Differential pair error',
    description: 'Differential pair routing constraint was violated.',
    retryable: false,
  },
  [ErrorCode.SIMULATION_CONVERGENCE]: {
    code: ErrorCode.SIMULATION_CONVERGENCE,
    httpStatus: 422,
    severity: ErrorSeverity.WARNING,
    label: 'Simulation did not converge',
    description: 'Newton-Raphson iteration did not converge within the maximum step count.',
    retryable: true,
  },
  [ErrorCode.SIMULATION_LIMIT_EXCEEDED]: {
    code: ErrorCode.SIMULATION_LIMIT_EXCEEDED,
    httpStatus: 422,
    severity: ErrorSeverity.ERROR,
    label: 'Simulation limit exceeded',
    description: 'The simulation exceeded maximum allowed nodes, steps, or duration.',
    retryable: false,
  },
  [ErrorCode.SIMULATION_MODEL_INVALID]: {
    code: ErrorCode.SIMULATION_MODEL_INVALID,
    httpStatus: 400,
    severity: ErrorSeverity.ERROR,
    label: 'Invalid SPICE model',
    description: 'SPICE model parameters are missing or invalid.',
    retryable: false,
  },
  [ErrorCode.SIMULATION_SINGULAR_MATRIX]: {
    code: ErrorCode.SIMULATION_SINGULAR_MATRIX,
    httpStatus: 422,
    severity: ErrorSeverity.ERROR,
    label: 'Singular matrix',
    description: 'The circuit matrix is singular (circuit may have floating nodes or short circuits).',
    retryable: false,
  },
  [ErrorCode.SIMULATION_MONTE_CARLO_LIMIT]: {
    code: ErrorCode.SIMULATION_MONTE_CARLO_LIMIT,
    httpStatus: 422,
    severity: ErrorSeverity.ERROR,
    label: 'Monte Carlo limit exceeded',
    description: 'Monte Carlo analysis exceeded the maximum iteration or sample count.',
    retryable: false,
  },
  [ErrorCode.SIMULATION_TIMESTEP]: {
    code: ErrorCode.SIMULATION_TIMESTEP,
    httpStatus: 422,
    severity: ErrorSeverity.WARNING,
    label: 'Timestep too small',
    description: 'Transient analysis adaptive timestep became smaller than minimum.',
    retryable: true,
  },
  [ErrorCode.SIMULATION_WEBGPU_UNAVAILABLE]: {
    code: ErrorCode.SIMULATION_WEBGPU_UNAVAILABLE,
    httpStatus: 200,
    severity: ErrorSeverity.INFO,
    label: 'WebGPU unavailable',
    description: 'WebGPU is not available; falling back to CPU computation.',
    retryable: false,
  },
  [ErrorCode.SIMULATION_THERMAL_FAILED]: {
    code: ErrorCode.SIMULATION_THERMAL_FAILED,
    httpStatus: 422,
    severity: ErrorSeverity.ERROR,
    label: 'Thermal analysis failed',
    description: 'Thermal resistance network solver failed to converge.',
    retryable: true,
  },
  [ErrorCode.SIMULATION_PDN_ERROR]: {
    code: ErrorCode.SIMULATION_PDN_ERROR,
    httpStatus: 422,
    severity: ErrorSeverity.ERROR,
    label: 'PDN analysis error',
    description: 'Power delivery network impedance analysis encountered an error.',
    retryable: true,
  },
  [ErrorCode.SIMULATION_SI_ERROR]: {
    code: ErrorCode.SIMULATION_SI_ERROR,
    httpStatus: 422,
    severity: ErrorSeverity.ERROR,
    label: 'Signal integrity error',
    description: 'Signal integrity analysis (crosstalk, eye diagram, etc.) failed.',
    retryable: true,
  },
  [ErrorCode.CIRCUIT_DSL_EVAL_ERROR]: {
    code: ErrorCode.CIRCUIT_DSL_EVAL_ERROR,
    httpStatus: 400,
    severity: ErrorSeverity.ERROR,
    label: 'Circuit DSL evaluation error',
    description: 'Circuit-as-code DSL script failed to evaluate.',
    retryable: false,
  },
  [ErrorCode.CIRCUIT_DSL_TIMEOUT]: {
    code: ErrorCode.CIRCUIT_DSL_TIMEOUT,
    httpStatus: 408,
    severity: ErrorSeverity.ERROR,
    label: 'Circuit DSL timeout',
    description: 'Circuit DSL sandbox watchdog terminated execution (exceeded time limit).',
    retryable: false,
  },
};
