/**
 * 3xxx — Export & Generation error catalog entries.
 */

import { ErrorCode } from './error-codes';
import { ErrorSeverity } from './error-types';
import type { ErrorCatalogEntry } from './error-types';

export const exportCatalog: Partial<Record<ErrorCode, ErrorCatalogEntry>> = {
  [ErrorCode.EXPORT_FAILED]: {
    code: ErrorCode.EXPORT_FAILED,
    httpStatus: 500,
    severity: ErrorSeverity.ERROR,
    label: 'Export failed',
    description: 'A generic export operation failed. See details for the specific cause.',
    retryable: true,
  },
  [ErrorCode.EXPORT_KICAD]: {
    code: ErrorCode.EXPORT_KICAD,
    httpStatus: 500,
    severity: ErrorSeverity.ERROR,
    label: 'KiCad export error',
    description: 'Failed to generate KiCad format output.',
    retryable: true,
  },
  [ErrorCode.EXPORT_EAGLE]: {
    code: ErrorCode.EXPORT_EAGLE,
    httpStatus: 500,
    severity: ErrorSeverity.ERROR,
    label: 'Eagle export error',
    description: 'Failed to generate Eagle format output.',
    retryable: true,
  },
  [ErrorCode.EXPORT_SPICE]: {
    code: ErrorCode.EXPORT_SPICE,
    httpStatus: 500,
    severity: ErrorSeverity.ERROR,
    label: 'SPICE export error',
    description: 'Failed to generate SPICE netlist output.',
    retryable: true,
  },
  [ErrorCode.EXPORT_GERBER]: {
    code: ErrorCode.EXPORT_GERBER,
    httpStatus: 500,
    severity: ErrorSeverity.ERROR,
    label: 'Gerber export error',
    description: 'Failed to generate Gerber photoplotter files.',
    retryable: true,
  },
  [ErrorCode.EXPORT_DRILL]: {
    code: ErrorCode.EXPORT_DRILL,
    httpStatus: 500,
    severity: ErrorSeverity.ERROR,
    label: 'Drill file error',
    description: 'Failed to generate Excellon drill files.',
    retryable: true,
  },
  [ErrorCode.EXPORT_PICK_AND_PLACE]: {
    code: ErrorCode.EXPORT_PICK_AND_PLACE,
    httpStatus: 500,
    severity: ErrorSeverity.ERROR,
    label: 'Pick-and-place export error',
    description: 'Failed to generate pick-and-place/centroid files.',
    retryable: true,
  },
  [ErrorCode.EXPORT_BOM]: {
    code: ErrorCode.EXPORT_BOM,
    httpStatus: 500,
    severity: ErrorSeverity.ERROR,
    label: 'BOM export error',
    description: 'Failed to generate Bill of Materials output.',
    retryable: true,
  },
  [ErrorCode.EXPORT_PDF]: {
    code: ErrorCode.EXPORT_PDF,
    httpStatus: 500,
    severity: ErrorSeverity.ERROR,
    label: 'PDF export error',
    description: 'Failed to generate PDF document.',
    retryable: true,
  },
  [ErrorCode.EXPORT_ODB_PLUS_PLUS]: {
    code: ErrorCode.EXPORT_ODB_PLUS_PLUS,
    httpStatus: 500,
    severity: ErrorSeverity.ERROR,
    label: 'ODB++ export error',
    description: 'Failed to generate ODB++ manufacturing output.',
    retryable: true,
  },
  [ErrorCode.EXPORT_IPC2581]: {
    code: ErrorCode.EXPORT_IPC2581,
    httpStatus: 500,
    severity: ErrorSeverity.ERROR,
    label: 'IPC-2581 export error',
    description: 'Failed to generate IPC-2581 XML output.',
    retryable: true,
  },
  [ErrorCode.EXPORT_STEP]: {
    code: ErrorCode.EXPORT_STEP,
    httpStatus: 500,
    severity: ErrorSeverity.ERROR,
    label: 'STEP export error',
    description: 'Failed to generate STEP 3D model output.',
    retryable: true,
  },
  [ErrorCode.EXPORT_DESIGN_REPORT]: {
    code: ErrorCode.EXPORT_DESIGN_REPORT,
    httpStatus: 500,
    severity: ErrorSeverity.ERROR,
    label: 'Design report error',
    description: 'Failed to generate design report.',
    retryable: true,
  },
  [ErrorCode.EXPORT_FMEA]: {
    code: ErrorCode.EXPORT_FMEA,
    httpStatus: 500,
    severity: ErrorSeverity.ERROR,
    label: 'FMEA report error',
    description: 'Failed to generate Failure Mode and Effects Analysis report.',
    retryable: true,
  },
  [ErrorCode.EXPORT_FIRMWARE_SCAFFOLD]: {
    code: ErrorCode.EXPORT_FIRMWARE_SCAFFOLD,
    httpStatus: 500,
    severity: ErrorSeverity.ERROR,
    label: 'Firmware scaffold error',
    description: 'Failed to generate firmware scaffold/template code.',
    retryable: true,
  },
  [ErrorCode.EXPORT_NETLIST]: {
    code: ErrorCode.EXPORT_NETLIST,
    httpStatus: 500,
    severity: ErrorSeverity.ERROR,
    label: 'Netlist export error',
    description: 'Failed to generate netlist output.',
    retryable: true,
  },
  [ErrorCode.EXPORT_FZPZ]: {
    code: ErrorCode.EXPORT_FZPZ,
    httpStatus: 500,
    severity: ErrorSeverity.ERROR,
    label: 'FZPZ export error',
    description: 'Failed to generate Fritzing component package.',
    retryable: true,
  },
  [ErrorCode.EXPORT_ETCHABLE_PCB]: {
    code: ErrorCode.EXPORT_ETCHABLE_PCB,
    httpStatus: 500,
    severity: ErrorSeverity.ERROR,
    label: 'Etchable PCB export error',
    description: 'Failed to generate home-etchable PCB artwork.',
    retryable: true,
  },
  [ErrorCode.EXPORT_LCSC_MAPPING]: {
    code: ErrorCode.EXPORT_LCSC_MAPPING,
    httpStatus: 500,
    severity: ErrorSeverity.ERROR,
    label: 'LCSC mapping export error',
    description: 'Failed to generate LCSC/JLCPCB component mapping CSV.',
    retryable: true,
  },
  [ErrorCode.EXPORT_DRC_GATE]: {
    code: ErrorCode.EXPORT_DRC_GATE,
    httpStatus: 422,
    severity: ErrorSeverity.WARNING,
    label: 'Export blocked by DRC',
    description: 'Export is blocked because the design has unresolved DRC violations.',
    retryable: false,
  },
};
