/**
 * AI Safety Mode Manager
 *
 * Provides a beginner-friendly safety layer for AI actions. When enabled (default),
 * caution and destructive actions require explicit user confirmation with
 * beginner-friendly explanations of what the action will do.
 *
 * Usage:
 *   const manager = AISafetyModeManager.getInstance();
 *   const classification = manager.classifyAction(action);
 *   if (classification !== 'safe') {
 *     // show confirmation dialog
 *   }
 *
 * React hook:
 *   const { enabled, classification, explanation, toggle, isDismissed, dismissAction } = useAISafetyMode();
 */

import { useCallback, useEffect, useState } from 'react';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Safety classification for an AI action. */
export type SafetyClassification = 'safe' | 'caution' | 'destructive';

/** Consequence entry shown in the confirmation dialog. */
export interface ActionConsequence {
  description: string;
}

/** Full safety info for an action, including classification, explanation, and consequences. */
export interface SafetyInfo {
  classification: SafetyClassification;
  explanation: string;
  consequences: ActionConsequence[];
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const STORAGE_KEY = 'protopulse-ai-safety-mode';
const DISMISSED_KEY = 'protopulse-ai-safety-dismissed';

/**
 * Actions that permanently remove or overwrite data. These always require
 * confirmation when safety mode is on.
 */
const DESTRUCTIVE_ACTION_TYPES = new Set([
  'remove_node',
  'remove_edge',
  'clear_canvas',
  'clear_validation',
  'remove_bom_item',
  'delete_node',
  'delete_edge',
  'clear_architecture',
  'replace_bom',
  'delete_component',
]);

/**
 * Actions that make significant but reversible changes. These require
 * confirmation with a gentler warning.
 */
const CAUTION_ACTION_TYPES = new Set([
  'generate_architecture',
  'add_multiple_nodes',
  'modify_component',
  'update_node',
  'connect_nodes',
  'auto_layout',
  'auto_fix_validation',
  'add_subcircuit',
  'auto_assign_pins',
  'optimize_bom',
  'rename_project',
  'update_description',
  'set_project_type',
  'import_design',
]);

/** Beginner-friendly explanations for each action type. */
const TEACHING_EXPLANATIONS: Record<string, string> = {
  // Destructive
  remove_node: 'This will permanently remove a component from your architecture diagram. Any connections to this component will also be deleted.',
  delete_node: 'This will permanently remove a component from your architecture diagram. Any connections to this component will also be deleted.',
  remove_edge: 'This will remove a connection between two components in your design. The components themselves will remain.',
  delete_edge: 'This will remove a connection between two components in your design. The components themselves will remain.',
  clear_canvas: 'This will remove ALL components and connections from your current design. Your entire architecture will be cleared.',
  clear_architecture: 'This will remove ALL components and connections from your current design. Your entire architecture will be cleared.',
  clear_validation: 'This will dismiss all current validation issues. These can be regenerated by running validation again.',
  remove_bom_item: 'This will remove a part from your Bill of Materials. The component will no longer be tracked for ordering.',
  replace_bom: 'This will replace your entire Bill of Materials with new data. All current BOM entries will be overwritten.',
  delete_component: 'This will permanently delete a component from your library. This cannot be undone.',

  // Caution
  generate_architecture: 'This will generate a complete architecture from scratch, replacing any existing nodes and edges. Your current design will be overwritten.',
  add_multiple_nodes: 'This will add several components to your design at once. You can remove them individually afterward if needed.',
  modify_component: 'This will change the properties of an existing component. The previous values will be overwritten.',
  update_node: 'This will update the properties of a component in your design, such as its label, type, or description.',
  connect_nodes: 'This will create a new electrical connection between two components. This defines how signals flow in your design.',
  auto_layout: 'This will automatically rearrange the positions of all components on your canvas. Your manual positioning will be replaced.',
  auto_fix_validation: 'This will attempt to automatically fix design issues found during validation. Changes may affect multiple components.',
  add_subcircuit: 'This will add a sub-circuit block to your design, which groups related components together.',
  auto_assign_pins: 'This will automatically map pins between components. Any existing pin assignments will be overwritten.',
  optimize_bom: 'This will modify your Bill of Materials to reduce cost or improve availability. Part selections may change.',
  rename_project: 'This will change the name of your project. The old name will be replaced.',
  update_description: 'This will update the project description. The previous description will be replaced.',
  set_project_type: 'This will change the project type classification, which affects AI suggestions and validation rules.',
  import_design: 'This will import an external design file into your project. Existing components may be affected.',
};

/** Consequence lists for each action type. */
const ACTION_CONSEQUENCES: Record<string, ActionConsequence[]> = {
  // Destructive
  remove_node: [
    { description: 'The component will be permanently removed from the diagram' },
    { description: 'All connections to/from this component will be deleted' },
    { description: 'Related BOM entries may become orphaned' },
  ],
  delete_node: [
    { description: 'The component will be permanently removed from the diagram' },
    { description: 'All connections to/from this component will be deleted' },
    { description: 'Related BOM entries may become orphaned' },
  ],
  remove_edge: [
    { description: 'The connection between components will be removed' },
    { description: 'Signal flow between the connected components will be broken' },
  ],
  delete_edge: [
    { description: 'The connection between components will be removed' },
    { description: 'Signal flow between the connected components will be broken' },
  ],
  clear_canvas: [
    { description: 'ALL components will be removed' },
    { description: 'ALL connections will be removed' },
    { description: 'This cannot be easily undone' },
  ],
  clear_architecture: [
    { description: 'ALL components will be removed' },
    { description: 'ALL connections will be removed' },
    { description: 'This cannot be easily undone' },
  ],
  clear_validation: [
    { description: 'All validation issues will be dismissed' },
    { description: 'You can re-run validation to regenerate them' },
  ],
  remove_bom_item: [
    { description: 'The part will be removed from the Bill of Materials' },
    { description: 'Ordering and cost tracking for this part will stop' },
  ],
  replace_bom: [
    { description: 'Your entire Bill of Materials will be replaced' },
    { description: 'All current part entries will be overwritten' },
    { description: 'Cost calculations will be recalculated' },
  ],
  delete_component: [
    { description: 'The component will be permanently deleted from your library' },
    { description: 'Any designs using this component will need manual updates' },
  ],

  // Caution
  generate_architecture: [
    { description: 'A new architecture will be generated from the AI description' },
    { description: 'Existing components and connections will be replaced' },
    { description: 'You can undo this action if needed' },
  ],
  add_multiple_nodes: [
    { description: 'Multiple components will be added to your design' },
    { description: 'You can remove individual components afterward' },
  ],
  modify_component: [
    { description: 'Component properties will be updated' },
    { description: 'Previous values will be overwritten' },
  ],
  update_node: [
    { description: 'The component label, type, or description may change' },
    { description: 'Previous values will be replaced' },
  ],
  connect_nodes: [
    { description: 'A new connection will be created between two components' },
    { description: 'This defines electrical signal flow in your design' },
  ],
  auto_layout: [
    { description: 'All components will be repositioned automatically' },
    { description: 'Your manual positioning will be replaced' },
  ],
  auto_fix_validation: [
    { description: 'The AI will attempt to fix design issues automatically' },
    { description: 'Multiple components may be modified' },
  ],
  add_subcircuit: [
    { description: 'A sub-circuit block will be added to your design' },
    { description: 'This groups related components together' },
  ],
  auto_assign_pins: [
    { description: 'Pin mappings will be automatically assigned' },
    { description: 'Existing pin assignments will be overwritten' },
  ],
  optimize_bom: [
    { description: 'BOM entries may be modified to optimize cost or availability' },
    { description: 'Part selections and quantities may change' },
  ],
  rename_project: [
    { description: 'The project name will change' },
  ],
  update_description: [
    { description: 'The project description will be updated' },
  ],
  set_project_type: [
    { description: 'The project type will change' },
    { description: 'AI suggestions and validation rules may be affected' },
  ],
  import_design: [
    { description: 'An external design will be imported' },
    { description: 'Existing components may be affected' },
  ],
};

// ---------------------------------------------------------------------------
// AISafetyModeManager
// ---------------------------------------------------------------------------

/**
 * Manages the AI safety mode state. Singleton per application.
 * Notifies subscribers on state changes. Persists to localStorage.
 */
export class AISafetyModeManager {
  private static instance: AISafetyModeManager | null = null;

  private _enabled: boolean;
  private _dismissedActions: Set<string>;
  private subscribers: Set<() => void>;

  constructor() {
    this._enabled = true;
    this._dismissedActions = new Set();
    this.subscribers = new Set();
    this.load();
  }

  /** Get or create the singleton instance. */
  static getInstance(): AISafetyModeManager {
    if (!AISafetyModeManager.instance) {
      AISafetyModeManager.instance = new AISafetyModeManager();
    }
    return AISafetyModeManager.instance;
  }

  /** Reset singleton (for testing). */
  static resetInstance(): void {
    AISafetyModeManager.instance = null;
  }

  // -------------------------------------------------------------------------
  // State
  // -------------------------------------------------------------------------

  /** Whether safety mode is currently enabled. */
  get enabled(): boolean {
    return this._enabled;
  }

  /** Set of action types the user has permanently dismissed. */
  get dismissedActions(): ReadonlySet<string> {
    return this._dismissedActions;
  }

  // -------------------------------------------------------------------------
  // Core API
  // -------------------------------------------------------------------------

  /** Toggle safety mode on/off. */
  toggle(): void {
    this._enabled = !this._enabled;
    this.save();
    this.notify();
  }

  /** Explicitly set safety mode on or off. */
  setEnabled(enabled: boolean): void {
    if (this._enabled !== enabled) {
      this._enabled = enabled;
      this.save();
      this.notify();
    }
  }

  /** Classify an action by its type string. */
  classifyAction(actionType: string): SafetyClassification {
    if (DESTRUCTIVE_ACTION_TYPES.has(actionType)) {
      return 'destructive';
    }
    if (CAUTION_ACTION_TYPES.has(actionType)) {
      return 'caution';
    }
    return 'safe';
  }

  /** Get a beginner-friendly explanation for an action type. */
  getTeachingExplanation(actionType: string): string {
    return TEACHING_EXPLANATIONS[actionType] ?? `This action will perform: ${actionType.replace(/_/g, ' ')}.`;
  }

  /** Get the full safety info for an action type. */
  getSafetyInfo(actionType: string): SafetyInfo {
    const classification = this.classifyAction(actionType);
    const explanation = this.getTeachingExplanation(actionType);
    const consequences = ACTION_CONSEQUENCES[actionType] ?? [
      { description: `The "${actionType.replace(/_/g, ' ')}" operation will be performed` },
    ];
    return { classification, explanation, consequences };
  }

  /**
   * Check whether an action needs confirmation.
   * Returns true if safety mode is on, the action is caution/destructive,
   * and the user has not dismissed this action type.
   */
  needsConfirmation(actionType: string): boolean {
    if (!this._enabled) {
      return false;
    }
    const classification = this.classifyAction(actionType);
    if (classification === 'safe') {
      return false;
    }
    if (this._dismissedActions.has(actionType)) {
      return false;
    }
    return true;
  }

  /**
   * Filter a list of actions into those that need confirmation and those that
   * are safe to execute immediately.
   */
  filterActions(actionTypes: string[]): {
    needsConfirmation: string[];
    safe: string[];
  } {
    const needs: string[] = [];
    const safe: string[] = [];
    for (const actionType of actionTypes) {
      if (this.needsConfirmation(actionType)) {
        needs.push(actionType);
      } else {
        safe.push(actionType);
      }
    }
    return { needsConfirmation: needs, safe };
  }

  /** Permanently dismiss confirmation for a specific action type. */
  dismissAction(actionType: string): void {
    this._dismissedActions.add(actionType);
    this.saveDismissed();
    this.notify();
  }

  /** Re-enable confirmation for a previously dismissed action type. */
  undismissAction(actionType: string): void {
    this._dismissedActions.delete(actionType);
    this.saveDismissed();
    this.notify();
  }

  /** Check if a specific action type has been dismissed. */
  isDismissed(actionType: string): boolean {
    return this._dismissedActions.has(actionType);
  }

  /** Clear all dismissed actions (re-enable confirmation for everything). */
  clearDismissed(): void {
    this._dismissedActions.clear();
    this.saveDismissed();
    this.notify();
  }

  // -------------------------------------------------------------------------
  // Subscribe / notify
  // -------------------------------------------------------------------------

  /** Subscribe to state changes. Returns an unsubscribe function. */
  subscribe(fn: () => void): () => void {
    this.subscribers.add(fn);
    return () => {
      this.subscribers.delete(fn);
    };
  }

  private notify(): void {
    for (const fn of Array.from(this.subscribers)) {
      fn();
    }
  }

  // -------------------------------------------------------------------------
  // Persistence
  // -------------------------------------------------------------------------

  private load(): void {
    try {
      const raw = localStorage.getItem(STORAGE_KEY);
      if (raw !== null) {
        this._enabled = raw === 'true';
      }
      const dismissedRaw = localStorage.getItem(DISMISSED_KEY);
      if (dismissedRaw) {
        const parsed = JSON.parse(dismissedRaw) as string[];
        if (Array.isArray(parsed)) {
          this._dismissedActions = new Set(parsed);
        }
      }
    } catch {
      // Ignore — use defaults
    }
  }

  private save(): void {
    try {
      localStorage.setItem(STORAGE_KEY, String(this._enabled));
    } catch {
      // Ignore storage errors
    }
  }

  private saveDismissed(): void {
    try {
      localStorage.setItem(DISMISSED_KEY, JSON.stringify(Array.from(this._dismissedActions)));
    } catch {
      // Ignore storage errors
    }
  }
}

// ---------------------------------------------------------------------------
// React Hook
// ---------------------------------------------------------------------------

/**
 * React hook for using the AI safety mode manager.
 * Re-renders on state changes.
 */
export function useAISafetyMode(): {
  enabled: boolean;
  toggle: () => void;
  setEnabled: (v: boolean) => void;
  classifyAction: (actionType: string) => SafetyClassification;
  getTeachingExplanation: (actionType: string) => string;
  getSafetyInfo: (actionType: string) => SafetyInfo;
  needsConfirmation: (actionType: string) => boolean;
  dismissAction: (actionType: string) => void;
  undismissAction: (actionType: string) => void;
  isDismissed: (actionType: string) => boolean;
  clearDismissed: () => void;
} {
  const manager = AISafetyModeManager.getInstance();
  const [, setTick] = useState(0);

  useEffect(() => {
    return manager.subscribe(() => {
      setTick((t) => t + 1);
    });
  }, [manager]);

  const toggle = useCallback(() => {
    manager.toggle();
  }, [manager]);

  const setEnabled = useCallback((v: boolean) => {
    manager.setEnabled(v);
  }, [manager]);

  const classifyAction = useCallback((actionType: string) => {
    return manager.classifyAction(actionType);
  }, [manager]);

  const getTeachingExplanation = useCallback((actionType: string) => {
    return manager.getTeachingExplanation(actionType);
  }, [manager]);

  const getSafetyInfo = useCallback((actionType: string) => {
    return manager.getSafetyInfo(actionType);
  }, [manager]);

  const needsConfirmation = useCallback((actionType: string) => {
    return manager.needsConfirmation(actionType);
  }, [manager]);

  const dismissAction = useCallback((actionType: string) => {
    manager.dismissAction(actionType);
  }, [manager]);

  const undismissAction = useCallback((actionType: string) => {
    manager.undismissAction(actionType);
  }, [manager]);

  const isDismissed = useCallback((actionType: string) => {
    return manager.isDismissed(actionType);
  }, [manager]);

  const clearDismissed = useCallback(() => {
    manager.clearDismissed();
  }, [manager]);

  return {
    enabled,
    toggle,
    setEnabled,
    classifyAction,
    getTeachingExplanation,
    getSafetyInfo,
    needsConfirmation,
    dismissAction,
    undismissAction,
    isDismissed,
    clearDismissed,
  };
}
