/* eslint-disable */
// Generated by tauri-specta — do not edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Frontend signals readiness + drains pending queue. Called once on mount
	 *  AFTER the listener is installed. Subsequent events emit live (and the
	 *  listener will pick them up).
	 */
	frontendReadyForProjectOpenRequests: () => __TAURI_INVOKE<PendingProjectOpenRequest[]>("frontend_ready_for_project_open_requests"),
	readUserSetting: (key: string) => typedError<string | null, string>(__TAURI_INVOKE("read_user_setting", { key })),
	writeUserSetting: (key: string, valueJson: string) => typedError<null, string>(__TAURI_INVOKE("write_user_setting", { key, valueJson })),
	readKanbanState: () => typedError<string | null, string>(__TAURI_INVOKE("read_kanban_state")),
	writeKanbanState: (valueJson: string) => typedError<null, string>(__TAURI_INVOKE("write_kanban_state", { valueJson })),
	readProjectDesignVariables: (projectId: string) => typedError<string | null, string>(__TAURI_INVOKE("read_project_design_variables", { projectId })),
	writeProjectDesignVariables: (projectId: string, valueJson: string) => typedError<null, string>(__TAURI_INVOKE("write_project_design_variables", { projectId, valueJson })),
	showSaveDialog: (title: string | null, defaultPath: string | null, filters: DialogFilter[] | null) => typedError<SaveDialogResult, string>(__TAURI_INVOKE("show_save_dialog", { title, defaultPath, filters })),
	showOpenDialog: (title: string | null, defaultPath: string | null, filters: DialogFilter[] | null, properties: string[] | null) => typedError<OpenDialogResult, string>(__TAURI_INVOKE("show_open_dialog", { title, defaultPath, filters, properties })),
	readFile: (filePath: string) => typedError<string, string>(__TAURI_INVOKE("read_file", { filePath })),
	writeFile: (filePath: string, data: string) => typedError<null, string>(__TAURI_INVOKE("write_file", { filePath, data })),
	getVersion: () => __TAURI_INVOKE<string>("get_version"),
	getPlatform: () => __TAURI_INVOKE<string>("get_platform"),
};

/* Types */
export type DialogFilter = {
	name: string,
	extensions: string[],
};

export type OpenDialogResult = {
	canceled: boolean,
	filePaths: string[],
};

export type PendingProjectOpenRequest = {
	/**
	 *  Matches the TS `ProjectOpenSource` union in
	 *  `client/src/lib/desktop/project-open-contract.ts`:
	 *  `"cold-start" | "warm-start" | "deep-link" | "menu" | "drop"`.
	 */
	source: string,
	path: string,
};

export type SaveDialogResult = {
	canceled: boolean,
	filePath: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

