import type { LucideIcon } from 'lucide-react';
import {
  LayoutDashboard,
  Blocks,
  ShieldCheck,
  ShoppingCart,
  FileOutput,
  Zap,
  CircuitBoard,
  Grid3X3,
  Microchip,
  KanbanSquare,
  BookMarked,
  Box,
  Globe,
  ShoppingBag,
  Warehouse,
  Plug,
  Code2,
  Wand2,
  Radio,
  Calculator,
  BookOpen,
  History,
  HeartPulse,
  MessageSquare,
  FileCode,
  GraduationCap,
  FlaskConical,
  PenTool,
  Lightbulb,
} from 'lucide-react';
import type { ViewMode } from '@/lib/project-context';

export interface NavItem {
  icon: LucideIcon;
  view: ViewMode;
  label: string;
}

export const navItems: NavItem[] = [
  { icon: LayoutDashboard, view: 'dashboard', label: 'Dashboard' },
  { icon: Blocks, view: 'architecture', label: 'Architecture' },
  { icon: CircuitBoard, view: 'schematic', label: 'Schematic' },
  { icon: FileCode, view: 'arduino', label: 'Arduino' },
  { icon: Code2, view: 'circuit_code', label: 'Circuit Code' },
  { icon: Grid3X3, view: 'breadboard', label: 'Breadboard' },
  { icon: Microchip, view: 'pcb', label: 'PCB' },
  { icon: PenTool, view: 'component_editor', label: 'Component Editor' },
  { icon: ShoppingCart, view: 'procurement', label: 'Procurement' },
  { icon: ShieldCheck, view: 'validation', label: 'Validation' },
  { icon: Zap, view: 'simulation', label: 'Simulation' },
  { icon: KanbanSquare, view: 'kanban', label: 'Tasks' },
  { icon: BookMarked, view: 'knowledge', label: 'Learn' },
  { icon: Box, view: 'viewer_3d', label: '3D View' },
  { icon: Globe, view: 'community', label: 'Community' },
  { icon: ShoppingBag, view: 'ordering', label: 'Order PCB' },
  { icon: Warehouse, view: 'storage', label: 'Inventory' },
  { icon: Plug, view: 'serial_monitor', label: 'Serial Monitor' },
  { icon: Calculator, view: 'calculators', label: 'Calculators' },
  { icon: BookOpen, view: 'design_patterns', label: 'Patterns' },
  { icon: Lightbulb, view: 'starter_circuits', label: 'Starter Circuits' },
  { icon: GraduationCap, view: 'labs', label: 'Labs' },
  { icon: History, view: 'design_history', label: 'History' },
  { icon: HeartPulse, view: 'lifecycle', label: 'Lifecycle' },
  { icon: MessageSquare, view: 'comments', label: 'Comments' },
  { icon: Wand2, view: 'generative_design', label: 'Generative' },
  { icon: Radio, view: 'digital_twin', label: 'Digital Twin' },
  { icon: FileOutput, view: 'output', label: 'Exports' },
];


export const tabDescriptions: Record<string, string> = {
  dashboard: 'Project overview and summary stats',
  output: 'Export design files and artifacts',
  architecture: 'Design system block diagram',
  component_editor: 'Design individual electronic components',
  schematic: 'Circuit schematic capture and net editing',
  breadboard: 'Virtual breadboard wiring and component placement',
  pcb: 'PCB footprint placement and trace routing',
  procurement: 'Manage bill of materials and sourcing',
  validation: 'Run design rule checks',
  design_history: 'Architecture snapshot history and visual diff',
  lifecycle: 'Component lifecycle tracking and supply chain risk',
  comments: 'Design review comments and discussions',
  calculators: 'Electronics engineering calculators',
  design_patterns: 'Reusable circuit design patterns with educational explanations',
  storage: 'Inventory tracking and storage location management',
  kanban: 'Track design tasks with a kanban board',
  knowledge: 'Electronics reference articles and learning resources',
  viewer_3d: '3D PCB board visualization and mechanical fit check',
  community: 'Browse and share community component library',
  ordering: 'Order PCBs from fabricators with DFM checks',
  simulation: 'SPICE simulation, AC/DC analysis, and waveform viewer',
  serial_monitor: 'Serial monitor for Arduino, ESP32, and other hardware devices',
  circuit_code: 'Arduino/C++ code editor with hardware-aware generation and upload',
  arduino: 'Embedded firmware workbench with board/library management and CLI integration',
  generative_design: 'AI-guided generative circuit design with evolutionary optimization',
  digital_twin: 'Live hardware digital twin with IoT telemetry and sim comparison',
  starter_circuits: 'Pre-built circuits with complete Arduino code for instant beginner gratification',
  labs: 'Guided lab assignments with objectives, steps, and grading criteria',
};

export const alwaysVisibleIds = new Set<ViewMode>([
  'dashboard',
  'architecture',
  'component_editor',
  'arduino',
  'calculators',
  'design_patterns',
  'kanban',
  'knowledge',
  'community',
  'ordering',
  'simulation',
  'serial_monitor',
  'circuit_code',
  'generative_design',
  'digital_twin',
  'design_history',
  'lifecycle',
  'comments',
  'output',
  'starter_circuits',
  'labs',
]);

