import { nodeData } from '../../chat-types';
import { downloadBlob } from '@/lib/csv';
import type { ActionHandler } from './types';

// ---------------------------------------------------------------------------
// Handlers
// ---------------------------------------------------------------------------

const downloadFile: ActionHandler = (action, ctx) => {
  const filename = action.filename as string | undefined;
  const content = action.content as string | undefined;
  const encoding = action.encoding as string | undefined;
  const mimeType = action.mimeType as string | undefined;
  if (!filename || !content) { return; }
  let blob: Blob;
  if (encoding === 'base64') {
    const binary = atob(content);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) { bytes[i] = binary.charCodeAt(i); }
    blob = new Blob([bytes], { type: mimeType || 'application/octet-stream' });
  } else {
    blob = new Blob([content], { type: mimeType || 'text/plain' });
  }
  downloadBlob(blob, filename);
  ctx.history.addToHistory(`Exported: ${filename}`, 'AI');
  ctx.output.addOutputLog(`[AI] Downloaded: ${filename}`);
};

const exportKicad: ActionHandler = (_action, ctx) => {
  const kicadContent = [
    '(kicad_sch (version 20230121) (generator "protopulse")',
    '  (paper "A4")',
  ];
  ctx.state.currentNodes.forEach((n) => {
    const nd = nodeData(n);
    kicadContent.push(`  (symbol (lib_id "${nd.type}:${nd.label}") (at ${n.position.x / 10} ${n.position.y / 10} 0))`);
    kicadContent.push(`    (property "Reference" "${nd.label}" (at 0 -2 0))`);
    kicadContent.push(`    (property "Value" "${nd.description || nd.type}" (at 0 2 0))`);
    kicadContent.push('  )');
  });
  ctx.state.currentEdges.forEach((e) => {
    const srcN = ctx.state.currentNodes.find((n) => n.id === e.source);
    const tgtN = ctx.state.currentNodes.find((n) => n.id === e.target);
    if (srcN && tgtN) {
      kicadContent.push(`  (wire (pts (xy ${srcN.position.x / 10} ${srcN.position.y / 10}) (xy ${tgtN.position.x / 10} ${tgtN.position.y / 10})))`);
    }
  });
  kicadContent.push(')');

  try {
    downloadBlob(new Blob([kicadContent.join('\n')], { type: 'text/plain' }), `${ctx.meta.projectName || 'design'}.kicad_sch`);
  } catch (err) {
    console.warn('KiCad export failed:', err);
  }

  ctx.history.addToHistory('Exported KiCad schematic', 'AI');
  ctx.output.addOutputLog(`[AI] Exported KiCad schematic with ${ctx.state.currentNodes.length} components`);
};

const exportSpice: ActionHandler = (_action, ctx) => {
  const spiceLines = [
    `* SPICE Netlist - ${ctx.meta.projectName}`,
    '* Generated by ProtoPulse',
    `* ${new Date().toISOString()}`,
    '',
  ];

  ctx.state.currentNodes.forEach((n, i) => {
    const nd = nodeData(n);
    const type = nd.type || 'generic';
    if (type === 'passive') {
      spiceLines.push(`R${i + 1} net_${n.id}_in net_${n.id}_out 10k ; ${nd.label}`);
    } else if (type === 'power') {
      spiceLines.push(`V${i + 1} net_${n.id}_out 0 3.3 ; ${nd.label}`);
    } else {
      spiceLines.push(`X${i + 1} ${String(nd.label).replace(/[^a-zA-Z0-9]/g, '_')} ; ${nd.description || type}`);
    }
  });

  spiceLines.push('', '.end');

  try {
    downloadBlob(new Blob([spiceLines.join('\n')], { type: 'text/plain' }), `${ctx.meta.projectName || 'design'}.cir`);
  } catch (err) {
    console.warn('SPICE export failed:', err);
  }

  ctx.history.addToHistory('Exported SPICE netlist', 'AI');
  ctx.output.addOutputLog(`[AI] Generated SPICE netlist with ${ctx.state.currentNodes.length} components`);
};

const previewGerber: ActionHandler = (_action, ctx) => {
  ctx.validation.addValidationIssue({
    severity: 'info',
    message: `PCB Preview: ${ctx.state.currentNodes.length} components, estimated board size ${Math.ceil(Math.max(...ctx.state.currentNodes.map((n) => n.position.x), 100) / 50)}cm x ${Math.ceil(Math.max(...ctx.state.currentNodes.map((n) => n.position.y), 100) / 50)}cm, ${ctx.state.currentEdges.length} traces to route.`,
    suggestion: 'For detailed PCB layout, export to KiCad and use the PCB editor. Consider 2-layer board for simple designs, 4-layer for high-speed or dense layouts.',
  });
  ctx.arch.setActiveView('output');
  ctx.history.addToHistory('Generated Gerber preview', 'AI');
  ctx.output.addOutputLog(`[AI] PCB layout preview: ${ctx.state.currentNodes.length} components, ${ctx.state.currentEdges.length} connections`);
};

const exportDesignReport: ActionHandler = (_action, ctx) => {
  const reportCost = ctx.state.currentBom.reduce((sum: number, b) => sum + (b.unitPrice * b.quantity), 0);
  const errorCount = ctx.state.currentIssues.filter((i) => i.severity === 'error').length;
  const warnCount = ctx.state.currentIssues.filter((i) => i.severity === 'warning').length;

  const report = [
    `# ${ctx.meta.projectName} — Design Report`,
    `Generated: ${new Date().toLocaleString()}`,
    '',
    '## Architecture Overview',
    `- Components: ${ctx.state.currentNodes.length}`,
    `- Connections: ${ctx.state.currentEdges.length}`,
    `- Component Types: ${Array.from(new Set(ctx.state.currentNodes.map((n) => nodeData(n).type))).join(', ')}`,
    '',
    '## Bill of Materials',
    `- Total Items: ${ctx.state.currentBom.length}`,
    `- Estimated Cost: $${reportCost.toFixed(2)}`,
    `- Suppliers: ${Array.from(new Set(ctx.state.currentBom.map((b) => b.supplier))).join(', ')}`,
    '',
    '## Validation Status',
    `- Errors: ${errorCount}`,
    `- Warnings: ${warnCount}`,
    `- Total Issues: ${ctx.state.currentIssues.length}`,
    '',
    '## Components',
    ...ctx.state.currentNodes.map((n) => {
      const nd = nodeData(n);
      return `- ${nd.label} (${nd.type}): ${nd.description || 'No description'}`;
    }),
    '',
    '## Recommendations',
    errorCount > 0 ? '- Fix all errors before proceeding to layout' : '- No critical errors',
    warnCount > 0 ? '- Review warnings for potential improvements' : '- No warnings',
    ctx.state.currentNodes.length < 3 ? '- Consider adding more components for a complete design' : '- Design complexity looks reasonable',
  ].join('\n');

  try {
    downloadBlob(new Blob([report], { type: 'text/markdown' }), `${ctx.meta.projectName || 'design'}_report.md`);
  } catch (err) {
    console.warn('Report export failed:', err);
  }

  ctx.arch.setActiveView('output');
  ctx.history.addToHistory('Generated design report', 'AI');
  ctx.output.addOutputLog(`[AI] Generated design report: ${ctx.state.currentNodes.length} components, $${reportCost.toFixed(2)} BOM cost`);
};

// ---------------------------------------------------------------------------
// Registry
// ---------------------------------------------------------------------------

export const exportHandlers: Record<string, ActionHandler> = {
  download_file: downloadFile,
  export_kicad: exportKicad,
  export_spice: exportSpice,
  preview_gerber: previewGerber,
  export_design_report: exportDesignReport,
};
