// design-sync controlled bundle entry — GENERATED (tools/gen). Tier: all.
// Re-exports scoped ProtoPulse UI components into one IIFE on window.ProtoPulse.
// `export *` carries named sub-exports for composition; default-exported
// components get an explicit `export { default as <Name> }`.

export * from "@/components/ui/accordion";
export * from "@/components/ui/AddToBomPrompt";
export { default as AddToBomPrompt } from "@/components/ui/AddToBomPrompt";
export * from "@/components/ui/alert-dialog";
export * from "@/components/ui/alert";
export * from "@/components/ui/aspect-ratio";
export * from "@/components/ui/avatar";
export * from "@/components/ui/badge";
export * from "@/components/ui/breadcrumb";
export * from "@/components/ui/button-group";
export * from "@/components/ui/button";
export * from "@/components/ui/calendar";
export * from "@/components/ui/card";
export * from "@/components/ui/carousel";
export * from "@/components/ui/chart";
export * from "@/components/ui/checkbox";
export * from "@/components/ui/collapsible";
export * from "@/components/ui/command";
export * from "@/components/ui/ConfidenceBadge";
export { default as ConfidenceBadge } from "@/components/ui/ConfidenceBadge";
export * from "@/components/ui/confirm-dialog";
export * from "@/components/ui/context-menu";
export * from "@/components/ui/dialog";
export * from "@/components/ui/drawer";
export * from "@/components/ui/dropdown-menu";
export * from "@/components/ui/EmbedDialog";
export { default as EmbedDialog } from "@/components/ui/EmbedDialog";
export * from "@/components/ui/empty";
export * from "@/components/ui/EmptyState";
export * from "@/components/ui/FeatureMaturityBadge";
export { default as FeatureMaturityBadge } from "@/components/ui/FeatureMaturityBadge";
export * from "@/components/ui/field";
export * from "@/components/ui/form";
export * from "@/components/ui/hover-card";
export * from "@/components/ui/input-group";
export * from "@/components/ui/input-otp";
export * from "@/components/ui/input";
export * from "@/components/ui/interactive-card";
export * from "@/components/ui/item";
export * from "@/components/ui/kbd";
export * from "@/components/ui/label";
export * from "@/components/ui/LessonModeOverlay";
export { default as LessonModeOverlay } from "@/components/ui/LessonModeOverlay";
export * from "@/components/ui/LibrarySuggestPopover";
export * from "@/components/ui/MentionBadge";
export { default as MentionBadge } from "@/components/ui/MentionBadge";
export * from "@/components/ui/menubar";
export * from "@/components/ui/navigation-menu";
export * from "@/components/ui/number-input";
export * from "@/components/ui/pagination";
export * from "@/components/ui/PanelSkeleton";
export * from "@/components/ui/popover";
export * from "@/components/ui/PredictionCard";
export { default as PredictionCard } from "@/components/ui/PredictionCard";
export * from "@/components/ui/PredictionPanel";
export { default as PredictionPanel } from "@/components/ui/PredictionPanel";
export * from "@/components/ui/progress";
export * from "@/components/ui/ProjectLoadingSkeleton";
export { default as ProjectLoadingSkeleton } from "@/components/ui/ProjectLoadingSkeleton";
export * from "@/components/ui/RadialMenu";
export { default as RadialMenu } from "@/components/ui/RadialMenu";
export * from "@/components/ui/radio-group";
export * from "@/components/ui/ReleaseConfidenceCard";
export { default as ReleaseConfidenceCard } from "@/components/ui/ReleaseConfidenceCard";
export * from "@/components/ui/resizable";
export * from "@/components/ui/RolePresetSelector";
export { default as RolePresetSelector } from "@/components/ui/RolePresetSelector";
export * from "@/components/ui/scroll-area";
export * from "@/components/ui/select";
export * from "@/components/ui/separator";
export * from "@/components/ui/sheet";
export * from "@/components/ui/sidebar";
export * from "@/components/ui/skeleton";
export * from "@/components/ui/slider";
export * from "@/components/ui/SmartHintToast";
export { default as SmartHintToast } from "@/components/ui/SmartHintToast";
export * from "@/components/ui/sonner";
export * from "@/components/ui/spinner";
export * from "@/components/ui/styled-tooltip";
export * from "@/components/ui/switch";
export * from "@/components/ui/table";
export * from "@/components/ui/tabs";
export * from "@/components/ui/textarea";
export * from "@/components/ui/toast";
export * from "@/components/ui/toggle-group";
export * from "@/components/ui/toggle";
export * from "@/components/ui/tooltip";
export * from "@/components/ui/TrustReceiptCard";
export { default as TrustReceiptCard } from "@/components/ui/TrustReceiptCard";
export * from "@/components/ui/ViewOnboardingHint";
export { default as ViewOnboardingHint } from "@/components/ui/ViewOnboardingHint";
