/**
 * IPC contract drift test (Phase 1 Task 1.5).
 *
 * The IPC contract is now generated end-to-end by `tauri-specta`:
 *
 *   Rust `#[tauri::command] #[specta::specta]` functions
 *     -> src-tauri/src/lib.rs (single source of truth)
 *     -> `cargo run --bin export_bindings --manifest-path src-tauri/Cargo.toml`
 *     -> client/src/lib/bindings.ts (committed, never hand-edited)
 *     -> consumed by client/src/lib/tauri-api.ts via `import { commands } from './bindings'`
 *     -> consumed by application code through the `DesktopAPI` adapter
 *
 * Three drift-prevention layers stack:
 *
 *   1. **TypeScript compilation** (npm run check) — catches signature
 *      mismatches between commands.X() and DesktopAPI/callers at build time.
 *   2. **Freshness test** (tauri-bindings-freshness.test.ts) — catches missing
 *      bindings.ts and missing/wrong command names.
 *   3. **THIS TEST** — catches the case where bindings.ts is checked in but
 *      stale relative to lib.rs (someone added a Rust command without running
 *      `cargo run --bin export_bindings`).
 *
 * The check is a static parse — no `cargo run` needed inside the test. It
 * works by extracting command names from both sides and demanding an exact
 * set match.
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const repoRoot = resolve(__dirname, "..", "..", "..", "..");
const libRsPath = resolve(repoRoot, "src-tauri", "src", "lib.rs");
const bindingsPath = resolve(repoRoot, "client", "src", "lib", "bindings.ts");

const libRs = readFileSync(libRsPath, "utf8");
const bindings = readFileSync(bindingsPath, "utf8");

/**
 * Extract registered command names from specta_builder's collect_commands![] list.
 *
 * This is the runtime source of truth: commands can be defined in other
 * modules (e.g., desktop_store::read_user_setting) and still be registered
 * here. Parsing only local #[tauri::command] fn declarations misses those.
 */
function rustCommandNames(): string[] {
  const names = new Set<string>();

  const collectMatch = libRs.match(/collect_commands!\[([\s\S]*?)\]/m);
  if (collectMatch) {
    const items = collectMatch[1]
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean);

    for (const item of items) {
      // Supports both `read_file` and `desktop_store::read_user_setting`.
      const terminal = item.split("::").pop() ?? item;
      if (/^[a-z_][a-z_0-9]*$/.test(terminal)) {
        names.add(terminal);
      }
    }
  }

  return Array.from(names).sort();
}

/**
 * Extract command names from the generated bindings.ts.
 *
 * tauri-specta emits an `export const commands = { name: ..., name2: ... }`
 * object. The TS names are camelCased; we convert back to snake_case so the
 * comparison runs in a single representation.
 */
function bindingsCommandNames(): string[] {
  const match = bindings.match(/export\s+const\s+commands\s*=\s*\{([\s\S]*?)\}\s*;/);
  if (!match) return [];
  const body = match[1];
  // Match property keys at the start of each line: `\tname: (...) => ...`
  // Be permissive on whitespace — tauri-specta uses tabs in v2.0.0-rc.25.
  const re = /^\s*([a-zA-Z][a-zA-Z0-9]*)\s*:/gm;
  const names = new Set<string>();
  let m: RegExpExecArray | null;
  while ((m = re.exec(body)) !== null) {
    const camel = m[1];
    // camelCase -> snake_case
    const snake = camel.replace(/[A-Z]/g, (c) => "_" + c.toLowerCase());
    names.add(snake);
  }
  return Array.from(names).sort();
}

describe("IPC contract drift (Phase 1 Task 1.5)", () => {
  it("bindings.ts carries the auto-generation header", () => {
    expect(
      bindings.includes("Generated by tauri-specta"),
      "bindings.ts must include the tauri-specta auto-generation header — it must NEVER be hand-edited",
    ).toBe(true);
  });

  it("bindings.ts and lib.rs agree on the exact command set", () => {
    const rust = rustCommandNames();
    const ts = bindingsCommandNames();
    expect(rust.length, "no Rust commands discovered — extraction regex broken").toBeGreaterThan(0);
    expect(ts.length, "no TS commands discovered — extraction regex broken").toBeGreaterThan(0);

    const inRustNotTs = rust.filter((n) => !ts.includes(n));
    const inTsNotRust = ts.filter((n) => !rust.includes(n));

    if (inRustNotTs.length > 0 || inTsNotRust.length > 0) {
      const msg = [
        "IPC contract drift detected between src-tauri/src/lib.rs and client/src/lib/bindings.ts.",
        `  Rust commands not in bindings.ts: ${JSON.stringify(inRustNotTs)}`,
        `  TS commands not in lib.rs:        ${JSON.stringify(inTsNotRust)}`,
        "",
        "  Regenerate bindings:",
        "    cargo run --bin export_bindings --manifest-path src-tauri/Cargo.toml",
        "",
        "  Then commit the resulting bindings.ts diff.",
      ].join("\n");
      expect.fail(msg);
    }

    expect(ts).toEqual(rust);
  });

  it("rules out the historical mismatched command names from raw invoke", () => {
    // Pre-tauri-specta, the bridge called read_file_contents/write_file_contents/get_app_version
    // — names Rust never registered. Those names must NEVER appear in bindings.ts.
    expect(bindings.includes("read_file_contents")).toBe(false);
    expect(bindings.includes("write_file_contents")).toBe(false);
    expect(bindings.includes("get_app_version")).toBe(false);
  });

  it("documents the regeneration command in the bindings header", () => {
    // The header should give devs the exact regen command so they don't have
    // to dig through docs when a drift error fires.
    const header = bindings.split("\n").slice(0, 10).join("\n");
    expect(
      /tauri-specta/i.test(header),
      "bindings.ts header should mention tauri-specta so devs know how it was generated",
    ).toBe(true);
  });
});
