// Motion tokens. Every transition, animation, setTimeout, and setInterval
// that affects perceived motion reads its timing from here.
//
// Durations are numbers (milliseconds). When a CSS rule needs a duration
// string, use cssDuration(MOTION.quick) or read the mirrored --motion-*-ms
// custom property generated by the tokens plugin.

export const MOTION = Object.freeze({
  // Named durations used across the UI.
  quick: 280,       // hover state, small affordance changes
  surface: 420,     // panels, menus, overlays
  layout: 520,      // node size/position during graph layout
  viewport: 450,    // setCenter / pan animations
  compass: 940,     // TopBar compass flourish
  caretBlink: 1000, // presentation caret

  // Hover scheduling (short timeouts, not CSS durations).
  hoverEnter: 72,
  hoverEnterSettle: 48,
  hoverExit: 140,

  // Graph-runtime timing.
  runtimePoll: 1200,           // runtime state poll interval
  guidedFlowStep: 1500,        // default delay between guided flow steps
  guidedFlowStepMin: 400,      // lower clamp for guided flow step delay
  graphReadyDelay: 200,        // delay after mount before first fitView
  statusBarRefresh: 30000,     // timestamp rerender cadence
  menuHide: 220,               // map-selector menu hide timeout
  nodeVisibility: 30,          // node appear delay
  revealIndexStep: 40,         // staggered function-reveal per index
  revealIndexMax: 140,         // maximum index-driven reveal delay
  revealActivation: 24,        // final activation step after reveal
  transitionTrigger: 10,       // microtask-like trigger for transition start
  fadeOut: 320,                // floating description fade-out
  typeInterval: 16,            // presentation caption typewriter
  mapAffordanceReset: 1600,    // clipboard-copy affordance reset
  zoomButton: 300,             // zoom in/out button easing
  fitView: 500,                // fitView button easing
})

export const EASING = Object.freeze({
  smooth: 'cubic-bezier(0.2, 0.82, 0.2, 1)',
  soft: 'cubic-bezier(0.25, 0.1, 0.25, 1)',
  compass: 'cubic-bezier(0.22, 0.74, 0.2, 1)',
  ease: 'ease',
})

// Helper: express a MOTION value as a CSS duration string.
export function cssDuration(ms) {
  return `${ms}ms`
}

// Helper: one-shot transition shorthand. transition('opacity', MOTION.quick, EASING.soft).
export function transition(property, duration, easing = EASING.soft) {
  return `${property} ${cssDuration(duration)} ${easing}`
}
