/**
 * BOM Exporter — Multi-format CSV export for BOM data.
 *
 * Pure function library. No Express routes, no side effects.
 * Supports JLCPCB, Mouser, Digi-Key, and generic CSV output.
 */

import type { BomItem } from '@shared/schema';
import {
  type BomItemData,
  type ComponentPartData,
  type ExportResult,
  csvRow as sharedCsvRow,
  escapeCSV,
  metaStr,
  sanitizeFilename,
} from './types';

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export type BomExportFormat = 'jlcpcb' | 'mouser' | 'digikey' | 'generic';

export interface BomExportOptions {
  format: BomExportFormat;
  /** Include the header row. Default: true */
  includeHeader?: boolean;
  /** Merge rows with identical partNumber, summing quantities. Default: false */
  groupByPartNumber?: boolean;
}

// ---------------------------------------------------------------------------
// Internal: row type narrowed to the fields we actually use
// ---------------------------------------------------------------------------

/**
 * Minimal subset of BomItem needed for export.
 * Accepts the full Drizzle‑inferred BomItem (which has extra fields like
 * deletedAt, updatedAt) without requiring callers to strip them.
 */
type BomItemRow = Pick<
  BomItem,
  | 'id'
  | 'projectId'
  | 'partNumber'
  | 'manufacturer'
  | 'description'
  | 'quantity'
  | 'unitPrice'
  | 'totalPrice'
  | 'supplier'
  | 'stock'
  | 'status'
  | 'leadTime'
>;

// ---------------------------------------------------------------------------
// CSV utilities
// ---------------------------------------------------------------------------

/** RFC 4180 CSV escaping: quote the field if it contains comma, quote, or newline. */
function escapeCsvField(value: string): string {
  if (value.includes(',') || value.includes('"') || value.includes('\n') || value.includes('\r')) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

function csvRow(fields: string[]): string {
  return fields.map(escapeCsvField).join(',');
}

// ---------------------------------------------------------------------------
// Grouping helper
// ---------------------------------------------------------------------------

/**
 * Merge rows sharing the same partNumber.
 * Quantities are summed; totalPrice is recalculated as quantity * unitPrice.
 * All other fields are taken from the first occurrence.
 *
 * NOTE: We intentionally avoid `for...of` on Map (downlevelIteration).
 */
function groupByPartNumber(items: readonly BomItemRow[]): BomItemRow[] {
  const map = new Map<string, BomItemRow>();

  items.forEach((item) => {
    const existing = map.get(item.partNumber);
    if (existing) {
      const newQuantity = existing.quantity + item.quantity;
      const unitPrice = parseFloat(existing.unitPrice);
      const newTotal = (newQuantity * unitPrice).toFixed(4);
      map.set(item.partNumber, {
        ...existing,
        quantity: newQuantity,
        totalPrice: newTotal,
      });
    } else {
      // Clone so we never mutate the caller's data
      map.set(item.partNumber, { ...item });
    }
  });

  const result: BomItemRow[] = [];
  map.forEach((value) => {
    result.push(value);
  });
  return result;
}

// ---------------------------------------------------------------------------
// Summary comment
// ---------------------------------------------------------------------------

function buildSummaryComment(items: readonly BomItemRow[]): string {
  let total = 0;
  items.forEach((item) => {
    total += parseFloat(item.totalPrice) || 0;
  });
  return `# Generated by ProtoPulse — ${items.length} line items, Total: $${total.toFixed(2)}`;
}

// ---------------------------------------------------------------------------
// Format-specific exporters
// ---------------------------------------------------------------------------

/**
 * JLCPCB CSV format.
 *
 * Columns: Comment, Designator, Footprint, LCSC Part #
 * - Comment       = description
 * - Designator    = partNumber (acts as reference designator)
 * - Footprint     = extracted from description if recognisable, else empty
 * - LCSC Part #   = partNumber when supplier is LCSC, else empty
 */
export function exportBomJlcpcb(items: BomItemRow[]): string {
  const header = csvRow(['Comment', 'Designator', 'Footprint', 'LCSC Part #']);
  const rows = items.map((item) => {
    const footprint = extractFootprint(item.description);
    const lcscPart = item.supplier === 'LCSC' ? item.partNumber : '';
    return csvRow([item.description, item.partNumber, footprint, lcscPart]);
  });
  return [header, ...rows].join('\n');
}

/**
 * Mouser CSV format.
 *
 * Columns: Manufacturer Part Number, Manufacturer, Quantity, Description, Unit Price
 */
export function exportBomMouser(items: BomItemRow[]): string {
  const header = csvRow([
    'Manufacturer Part Number',
    'Manufacturer',
    'Quantity',
    'Description',
    'Unit Price',
  ]);
  const rows = items.map((item) =>
    csvRow([
      item.partNumber,
      item.manufacturer,
      String(item.quantity),
      item.description,
      item.unitPrice,
    ]),
  );
  return [header, ...rows].join('\n');
}

/**
 * Digi-Key CSV format.
 *
 * Columns: Digi-Key Part Number, Manufacturer Part Number, Manufacturer,
 *          Quantity, Description, Unit Price, Extended Price
 * - Digi-Key Part Number = partNumber
 * - Extended Price        = totalPrice
 */
export function exportBomDigikey(items: BomItemRow[]): string {
  const header = csvRow([
    'Digi-Key Part Number',
    'Manufacturer Part Number',
    'Manufacturer',
    'Quantity',
    'Description',
    'Unit Price',
    'Extended Price',
  ]);
  const rows = items.map((item) =>
    csvRow([
      item.partNumber,
      item.partNumber,
      item.manufacturer,
      String(item.quantity),
      item.description,
      item.unitPrice,
      item.totalPrice,
    ]),
  );
  return [header, ...rows].join('\n');
}

/**
 * Generic CSV format — all fields included.
 *
 * Columns: Part Number, Manufacturer, Description, Quantity, Unit Price,
 *          Total Price, Supplier, Stock, Status, Lead Time
 */
export function exportBomGeneric(items: BomItemRow[]): string {
  const header = csvRow([
    'Part Number',
    'Manufacturer',
    'Description',
    'Quantity',
    'Unit Price',
    'Total Price',
    'Supplier',
    'Stock',
    'Status',
    'Lead Time',
  ]);
  const rows = items.map((item) =>
    csvRow([
      item.partNumber,
      item.manufacturer,
      item.description,
      String(item.quantity),
      item.unitPrice,
      item.totalPrice,
      item.supplier,
      String(item.stock),
      item.status,
      item.leadTime ?? '',
    ]),
  );
  return [header, ...rows].join('\n');
}

// ---------------------------------------------------------------------------
// Unified entry point
// ---------------------------------------------------------------------------

const FORMAT_EXPORTERS: Record<BomExportFormat, (items: BomItemRow[]) => string> = {
  jlcpcb: exportBomJlcpcb,
  mouser: exportBomMouser,
  digikey: exportBomDigikey,
  generic: exportBomGeneric,
};

/**
 * Export BOM items to the requested CSV format.
 *
 * @param items   - BOM rows (typically from `storage.getBomItems(projectId)`)
 * @param options - Format selection and optional flags
 * @returns       - Complete CSV string ready to be served or saved
 */
export function exportBom(items: BomItemRow[], options: BomExportOptions): string {
  const {
    format,
    includeHeader = true,
    groupByPartNumber: shouldGroup = false,
  } = options;

  const processed = shouldGroup ? groupByPartNumber(items) : items;
  const exporter = FORMAT_EXPORTERS[format];
  const csv = exporter(processed);

  // The format-specific exporters always produce a header as the first line.
  // If the caller opted out of headers, strip it.
  const lines = csv.split('\n');
  const dataLines = includeHeader ? lines : lines.slice(1);

  const summary = buildSummaryComment(processed);
  return [summary, ...dataLines].join('\n');
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Best-effort extraction of a footprint string from a part description.
 *
 * Common patterns:
 *   "100nF Capacitor 0402"           → "0402"
 *   "STM32F103 LQFP-48"             → "LQFP-48"
 *   "10uH Inductor, 0805 package"   → "0805"
 *   "Resistor 1206 1%"              → "1206"
 *
 * Returns empty string when no known pattern is found.
 */
function extractFootprint(description: string): string {
  // Metric SMD sizes (0201, 0402, 0603, 0805, 1206, 1210, 1812, 2010, 2512, etc.)
  const smdMatch = description.match(/\b(0201|0402|0603|0805|1206|1210|1812|2010|2512)\b/);
  if (smdMatch) return smdMatch[1];

  // Common package names with optional pin count (QFP-48, SOIC-8, SOT-23, BGA-256, etc.)
  const pkgMatch = description.match(
    /\b(LQFP|QFP|TQFP|QFN|DFN|BGA|SOIC|SOP|SSOP|TSSOP|SOT|TO|DIP|PLCC|LGA|CSP|WLCSP)[-‑]?\d*\b/i,
  );
  if (pkgMatch) return pkgMatch[0].toUpperCase();

  return '';
}

// ---------------------------------------------------------------------------
// Legacy API — original export-generators.ts signatures used by ai-tools.ts
// ---------------------------------------------------------------------------

export function generateGenericBomCsv(
  bom: BomItemData[],
  projectName: string,
): ExportResult {
  const header = sharedCsvRow([
    'Part Number',
    'Manufacturer',
    'Description',
    'Quantity',
    'Unit Price',
    'Total Price',
    'Supplier',
    'Status',
    'Stock',
    'Lead Time',
  ]);

  const rows = bom.map((item) =>
    sharedCsvRow([
      item.partNumber,
      item.manufacturer,
      item.description,
      item.quantity,
      item.unitPrice,
      item.totalPrice,
      item.supplier,
      item.status,
      item.stock,
      item.leadTime,
    ]),
  );

  return {
    content: [header, ...rows].join('\n'),
    encoding: 'utf8',
    mimeType: 'text/csv',
    filename: `${sanitizeFilename(projectName)}_BOM.csv`,
  };
}

export function generateJlcpcbBom(
  bom: BomItemData[],
  parts: ComponentPartData[],
): ExportResult {
  const header = sharedCsvRow(['Comment', 'Designator', 'Footprint', 'LCSC Part #']);

  // Build lookup: MPN → part meta
  const mpnToMeta = new Map<string, Record<string, unknown>>();
  for (const part of parts) {
    const mpn = metaStr(part.meta, 'mpn');
    if (mpn) {
      mpnToMeta.set(mpn.toLowerCase(), part.meta);
    }
  }

  // Counters for auto-generated reference designators by prefix
  const refDesCounters = new Map<string, number>();

  function nextRefDes(prefix: string): string {
    const current = (refDesCounters.get(prefix) ?? 0) + 1;
    refDesCounters.set(prefix, current);
    return `${prefix}${current}`;
  }

  /** Guess a ref-des prefix from a description. */
  function guessPrefix(description: string): string {
    const desc = description.toLowerCase();
    if (desc.includes('resistor') || desc.includes('res ')) return 'R';
    if (desc.includes('capacitor') || desc.includes('cap ')) return 'C';
    if (desc.includes('inductor') || desc.includes('ind ')) return 'L';
    if (desc.includes('diode') || desc.includes('led')) return 'D';
    if (desc.includes('transistor') || desc.includes('mosfet') || desc.includes('bjt')) return 'Q';
    if (desc.includes('connector') || desc.includes('header')) return 'J';
    if (desc.includes('crystal') || desc.includes('oscillator')) return 'Y';
    return 'U';
  }

  const rows = bom.map((item) => {
    const meta = mpnToMeta.get(item.partNumber.toLowerCase());

    let designator: string;
    if (meta) {
      const existingRef = metaStr(meta, 'referenceDesignator');
      designator = existingRef || nextRefDes(guessPrefix(item.description));
    } else {
      designator = nextRefDes(guessPrefix(item.description));
    }

    const footprint = meta ? metaStr(meta, 'footprint', 'Unknown') : 'Unknown';
    const lcsc = meta ? metaStr(meta, 'lcscPartNumber') : '';

    return sharedCsvRow([item.description, designator, footprint, lcsc]);
  });

  return {
    content: [header, ...rows].join('\n'),
    encoding: 'utf8',
    mimeType: 'text/csv',
    filename: 'JLCPCB_BOM.csv',
  };
}

export function generateMouserBom(bom: BomItemData[]): ExportResult {
  const header = sharedCsvRow([
    'Mouser Part #',
    'MFR Part #',
    'Manufacturer',
    'Quantity',
    'Description',
    'Unit Price',
  ]);

  const rows = bom.map((item) =>
    sharedCsvRow([
      '', // Mouser Part # — user fills in
      item.partNumber,
      item.manufacturer,
      item.quantity,
      item.description,
      item.unitPrice,
    ]),
  );

  return {
    content: [header, ...rows].join('\n'),
    encoding: 'utf8',
    mimeType: 'text/csv',
    filename: 'Mouser_BOM.csv',
  };
}

export function generateDigikeyBom(bom: BomItemData[]): ExportResult {
  const header = sharedCsvRow([
    'DigiKey Part #',
    'MFR Part #',
    'Manufacturer Name',
    'Quantity',
    'Unit Price',
    'Extended Price',
  ]);

  const rows = bom.map((item) =>
    sharedCsvRow([
      '', // DigiKey Part # — user fills in
      item.partNumber,
      item.manufacturer,
      item.quantity,
      item.unitPrice,
      item.totalPrice,
    ]),
  );

  return {
    content: [header, ...rows].join('\n'),
    encoding: 'utf8',
    mimeType: 'text/csv',
    filename: 'DigiKey_BOM.csv',
  };
}
