import type { Express } from 'express';
import { z } from 'zod';
import { requireProjectOwnership } from '../routes/auth-middleware';
import { asyncHandler, HttpError, parseIdParam, payloadLimit } from '../routes/utils';
import type { IStorage } from '../storage';
import type { InsertCircuitInstance } from '@shared/schema';

// We accept the layout generated by irToSchematicLayout from the client
const PinLayoutSchema = z.object({
  name: z.string(),
  x: z.number(),
  y: z.number(),
  netId: z.string(),
});

const ComponentLayoutSchema = z.object({
  id: z.string(),
  refdes: z.string(),
  partId: z.string().optional(),
  value: z.string().optional(),
  x: z.number(),
  y: z.number(),
  width: z.number(),
  height: z.number(),
  pins: z.array(PinLayoutSchema),
});

const NetSegmentSchema = z.object({
  x1: z.number(),
  y1: z.number(),
  x2: z.number(),
  y2: z.number(),
});

const NetPathSchema = z.object({
  netId: z.string(),
  name: z.string(),
  type: z.enum(['signal', 'power', 'ground']),
  segments: z.array(NetSegmentSchema),
});

const SchematicLayoutSchema = z.object({
  components: z.array(ComponentLayoutSchema),
  nets: z.array(NetPathSchema),
});

export function registerApplyCodeRoutes(app: Express, storage: IStorage): void {
  app.post('/api/projects/:projectId/circuits/apply-code', requireProjectOwnership, payloadLimit(16 * 1024), asyncHandler(async (req, res) => {
    const projectId = parseIdParam(req.params.projectId);
    const { circuitId: providedCircuitId, circuitName, layout } = req.body as { circuitId?: number; circuitName?: string; layout: z.infer<typeof SchematicLayoutSchema> };

    const parsedLayout = SchematicLayoutSchema.safeParse(layout);
    if (!parsedLayout.success) {
      return res.status(400).json({ message: 'Invalid layout payload' });
    }

    // 1. Fetch available component parts
    const parts = await storage.getComponentParts(projectId);

    // 2. Resolve Circuit
    let circuitId = providedCircuitId;
    if (!circuitId) {
      const circuit = await storage.createCircuitDesign({
        projectId,
        name: circuitName || 'Generated from Code',
      });
      circuitId = circuit.id;
    } else {
      // Verify circuit belongs to project
      const circuits = await storage.getCircuitDesigns(projectId);
      if (!circuits.some(c => c.id === circuitId)) {
        throw new HttpError('Circuit not found in project', 404);
      }
    }

    // 3. Map Components to Instances
    const irIdToInstanceId = new Map<string, number>();

    // We need to pre-allocate instance IDs or do it sequentially to get IDs for nets.
    // For simplicity, we'll insert them one by one or batch insert and fetch them.
    for (const comp of parsedLayout.data.components) {
      // Find matching part from project parts by string partId or name
      let dbPartId: number | null = null;
      if (comp.partId) {
        // Try to find exact standard library match or similar name
        const match = parts.find(p => p.name.toLowerCase().includes(comp.partId!.toLowerCase()) || (p.meta as any)?.partNumber === comp.partId);
        if (match) dbPartId = match.id;
      }
      
      const props: Record<string, string> = {};
      if (comp.value) props.value = comp.value;

      const created = await storage.createCircuitInstance({
        circuitId,
        partId: dbPartId,
        referenceDesignator: comp.refdes,
        schematicX: comp.x,
        schematicY: comp.y,
        properties: Object.keys(props).length > 0 ? props : undefined,
      });
      irIdToInstanceId.set(comp.id, created.id);
    }

    // 4. Map Nets and Wires
    for (const net of parsedLayout.data.nets) {
      const createdNet = await storage.createCircuitNet({
        circuitId,
        name: net.name,
        netType: net.type,
      });

      for (const seg of net.segments) {
        await storage.createCircuitWire({
          circuitId,
          netId: createdNet.id,
          view: 'schematic',
          points: [
            { x: seg.x1, y: seg.y1 },
            { x: seg.x2, y: seg.y2 }
          ],
        });
      }
    }

    res.json({ success: true, circuitId });
  }));
}
