import type { Express } from 'express';
import { z } from 'zod';
import { fromZodError } from 'zod-validation-error';
import type { IStorage } from '../storage';
import type { NetSegment } from './utils';
import { asyncHandler, parseIdParam, payloadLimit } from './utils';
import { computeNetlistDiff, type NetlistSnapshot, type NetSnapshot, type ComponentSnapshot } from '@shared/netlist-diff';

export function registerCircuitNetlistRoutes(app: Express, storage: IStorage): void {
  app.post('/api/circuits/:circuitId/netlist', payloadLimit(16 * 1024), asyncHandler(async (req, res) => {
    const circuitId = parseIdParam(req.params.circuitId);
    const { format = 'generic' } = req.body as { format?: 'generic' | 'spice' | 'kicad' };

    const circuit = await storage.getCircuitDesign(circuitId);
    if (!circuit) { return res.status(404).json({ message: 'Circuit not found' }); }

    const instances = await storage.getCircuitInstances(circuitId);
    const nets = await storage.getCircuitNets(circuitId);
    const parts = await storage.getComponentParts(circuit.projectId);

    const partsMap = new Map<number, typeof parts[0]>();
    for (const p of parts) { partsMap.set(p.id, p); }

    // Build connector alias map: "instId:pinName" -> "instId:pinId"
    // Net segments may reference pins by name (e.g. "PB0") or by id (e.g. "pin2")
    const connAlias = new Map<string, string>();
    for (const inst of instances) {
      const part = inst.partId != null ? partsMap.get(inst.partId) : undefined;
      const connectors = (part?.connectors ?? []) as Array<{ id: string; name: string }>;
      for (const c of connectors) {
        if (c.name !== c.id) {
          connAlias.set(`${inst.id}:${c.name}`, `${inst.id}:${c.id}`);
        }
      }
    }
    const resolveNetKey = (raw: string): string =>
      connAlias.get(raw) ?? raw;

    if (format === 'spice') {
      // SPICE netlist format
      const lines: string[] = [];
      lines.push(`* SPICE Netlist — ${circuit.name}`);
      lines.push('* Generated by ProtoPulse');
      lines.push('');

      // Map instance -> net connections (build pin->net lookup with alias resolution)
      const pinToNet = new Map<string, string>();
      for (const net of nets) {
        const segments = (net.segments ?? []) as NetSegment[];
        for (const seg of segments) {
          pinToNet.set(resolveNetKey(`${seg.fromInstanceId}:${seg.fromPin}`), net.name);
          pinToNet.set(resolveNetKey(`${seg.toInstanceId}:${seg.toPin}`), net.name);
        }
      }

      for (const inst of instances) {
        const part = inst.partId != null ? partsMap.get(inst.partId) : undefined;
        const meta = (part?.meta ?? {}) as Record<string, unknown>;
        const connectors = (part?.connectors ?? []) as Array<{ id: string; name: string }>;
        const family = ((meta.family as string) || '').toLowerCase();

        // Build pin list in order
        const pinNets = connectors.map((c) => {
          const netName = pinToNet.get(`${inst.id}:${c.id}`);
          return netName || '0'; // 0 = unconnected/ground in SPICE
        });

        // Component line: RefDes net1 net2 ... model/value
        const refDes = inst.referenceDesignator;
        const value = (meta.title as string) || family || '?';

        if (family === 'resistor') {
          lines.push(`${refDes} ${pinNets.join(' ')} ${value}`);
        } else if (family === 'capacitor') {
          lines.push(`${refDes} ${pinNets.join(' ')} ${value}`);
        } else if (family === 'inductor') {
          lines.push(`${refDes} ${pinNets.join(' ')} ${value}`);
        } else {
          // Generic subcircuit call
          lines.push(`X${refDes} ${pinNets.join(' ')} ${value}`);
        }
      }

      lines.push('');
      lines.push('.end');

      res.json({
        format: 'spice',
        netlist: lines.join('\n'),
        instanceCount: instances.length,
        netCount: nets.length,
      });
    } else if (format === 'kicad') {
      // KiCad netlist format (simplified)
      const lines: string[] = [];
      lines.push('(export (version D)');
      lines.push('  (design');
      lines.push(`    (source "${circuit.name}")`);
      lines.push('    (tool "ProtoPulse")');
      lines.push('  )');

      // Components
      lines.push('  (components');
      for (const inst of instances) {
        const part = inst.partId != null ? partsMap.get(inst.partId) : undefined;
        const meta = (part?.meta ?? {}) as Record<string, unknown>;
        lines.push(`    (comp (ref ${inst.referenceDesignator})`);
        lines.push(`      (value "${(meta.title as string) || ''}")`);
        lines.push(`      (footprint "${(meta.package as string) || ''}")`);
        lines.push('    )');
      }
      lines.push('  )');

      // Nets
      lines.push('  (nets');
      lines.push('    (net (code 0) (name ""))'); // unconnected net
      for (let i = 0; i < nets.length; i++) {
        const net = nets[i];
        const segments = (net.segments ?? []) as NetSegment[];
        lines.push(`    (net (code ${i + 1}) (name "${net.name}")`);
        for (const seg of segments) {
          const fromInst = instances.find((inst) => inst.id === seg.fromInstanceId);
          const toInst = instances.find((inst) => inst.id === seg.toInstanceId);
          // Resolve pin references to canonical IDs (handles name-vs-id mismatch)
          const fromPinId = resolveNetKey(`${seg.fromInstanceId}:${seg.fromPin}`).split(':')[1];
          const toPinId = resolveNetKey(`${seg.toInstanceId}:${seg.toPin}`).split(':')[1];
          if (fromInst) { lines.push(`      (node (ref ${fromInst.referenceDesignator}) (pin ${fromPinId}))`); }
          if (toInst) { lines.push(`      (node (ref ${toInst.referenceDesignator}) (pin ${toPinId}))`); }
        }
        lines.push('    )');
      }
      lines.push('  )');
      lines.push(')');

      res.json({
        format: 'kicad',
        netlist: lines.join('\n'),
        instanceCount: instances.length,
        netCount: nets.length,
      });
    } else {
      // Generic netlist format (JSON)
      const netlist = {
        circuit: { id: circuit.id, name: circuit.name },
        components: instances.map((inst) => {
          const part = inst.partId != null ? partsMap.get(inst.partId) : undefined;
          const meta = (part?.meta ?? {}) as Record<string, unknown>;
          const connectors = (part?.connectors ?? []) as Array<{ id: string; name: string }>;
          return {
            refDes: inst.referenceDesignator,
            partId: inst.partId,
            value: (meta.title as string) || '',
            family: (meta.family as string) || '',
            pins: connectors.map((c) => ({ id: c.id, name: c.name })),
          };
        }),
        nets: nets.map((net) => {
          const segments = (net.segments ?? []) as NetSegment[];
          return {
            name: net.name,
            type: net.netType,
            voltage: net.voltage,
            busWidth: net.busWidth,
            connections: segments.map((seg) => {
              const fromInst = instances.find((inst) => inst.id === seg.fromInstanceId);
              const toInst = instances.find((inst) => inst.id === seg.toInstanceId);
              return {
                from: { refDes: fromInst?.referenceDesignator || `?${seg.fromInstanceId}`, pin: seg.fromPin },
                to: { refDes: toInst?.referenceDesignator || `?${seg.toInstanceId}`, pin: seg.toPin },
              };
            }),
          };
        }),
      };

      res.json({
        format: 'generic',
        netlist,
        instanceCount: instances.length,
        netCount: nets.length,
      });
    }
  }));

  // ---------------------------------------------------------------------------
  // Netlist Diff / ECO — compare two circuit netlists
  // ---------------------------------------------------------------------------

  const diffSchema = z.object({
    baselineCircuitId: z.number().int().positive(),
  });

  app.post('/api/circuits/:circuitId/netlist-diff', payloadLimit(8 * 1024), asyncHandler(async (req, res) => {
    const currentCircuitId = parseIdParam(req.params.circuitId);
    const parsed = diffSchema.safeParse(req.body);
    if (!parsed.success) {
      return res.status(400).json({ message: fromZodError(parsed.error).toString() });
    }
    const { baselineCircuitId } = parsed.data;

    // Fetch both circuits
    const [currentCircuit, baselineCircuit] = await Promise.all([
      storage.getCircuitDesign(currentCircuitId),
      storage.getCircuitDesign(baselineCircuitId),
    ]);
    if (!currentCircuit) { return res.status(404).json({ message: 'Current circuit not found' }); }
    if (!baselineCircuit) { return res.status(404).json({ message: 'Baseline circuit not found' }); }

    // Fetch data for both circuits in parallel
    const [currentInstances, currentNets, currentParts, baselineInstances, baselineNets, baselineParts] = await Promise.all([
      storage.getCircuitInstances(currentCircuitId),
      storage.getCircuitNets(currentCircuitId),
      storage.getComponentParts(currentCircuit.projectId),
      storage.getCircuitInstances(baselineCircuitId),
      storage.getCircuitNets(baselineCircuitId),
      storage.getComponentParts(baselineCircuit.projectId),
    ]);

    // Build snapshot for current circuit
    const currentSnapshot = buildNetlistSnapshot(
      currentCircuit.name, currentInstances, currentNets, currentParts,
    );

    // Build snapshot for baseline circuit
    const baselineSnapshot = buildNetlistSnapshot(
      baselineCircuit.name, baselineInstances, baselineNets, baselineParts,
    );

    const diff = computeNetlistDiff(baselineSnapshot, currentSnapshot);

    res.json({
      baseline: { id: baselineCircuitId, name: baselineCircuit.name },
      current: { id: currentCircuitId, name: currentCircuit.name },
      diff,
    });
  }));
}

// ---------------------------------------------------------------------------
// Helper: build a NetlistSnapshot from database rows
// ---------------------------------------------------------------------------

function buildNetlistSnapshot(
  circuitName: string,
  instances: Array<{ id: number; partId: number | null; referenceDesignator: string }>,
  nets: Array<{ name: string; netType: string; segments: unknown }>,
  parts: Array<{ id: number; meta: unknown; connectors: unknown }>,
): NetlistSnapshot {
  const partsMap = new Map<number, typeof parts[0]>();
  for (const p of parts) { partsMap.set(p.id, p); }

  const components: ComponentSnapshot[] = instances.map((inst) => {
    const part = inst.partId != null ? partsMap.get(inst.partId) : undefined;
    const meta = (part?.meta ?? {}) as Record<string, unknown>;
    return {
      referenceDesignator: inst.referenceDesignator,
      partId: inst.partId,
      value: (meta.title as string) || (meta.family as string) || '',
    };
  });

  const netSnapshots: NetSnapshot[] = nets.map((net) => {
    const segments = (net.segments ?? []) as NetSegment[];
    const connections = segments.flatMap((seg) => {
      const fromInst = instances.find((i) => i.id === seg.fromInstanceId);
      const toInst = instances.find((i) => i.id === seg.toInstanceId);
      const result: Array<{ refDes: string; pin: string }> = [];
      if (fromInst) { result.push({ refDes: fromInst.referenceDesignator, pin: seg.fromPin }); }
      if (toInst) { result.push({ refDes: toInst.referenceDesignator, pin: seg.toPin }); }
      return result;
    });

    return {
      name: net.name,
      netType: net.netType,
      connections,
    };
  });

  return {
    circuitName,
    components,
    nets: netSnapshots,
  };
}
