import os
import json
import argparse
from datetime import datetime

def generate_moc(directory, output_file="MAP_OF_CONTENT.md"):
    """
    Generates a High-Intelligence Map of Content (MOC).
    Integrates Photos, Manifest Data, Datasheets, and Safety Reports.
    """
    root = os.path.abspath(directory)
    manifest_path = os.path.join(root, "99_Meta", "deep_inventory_manifest.json")
    datasheet_dir = os.path.join(root, "10_Atlas", "Datasheets")
    moc_path = os.path.join(root, output_file)
    
    manifest = {}
    if os.path.exists(manifest_path):
        with open(manifest_path, "r") as f:
            manifest = json.load(f)

    lines = []
    lines.append("---")
    lines.append(f"type: inventory_dashboard")
    lines.append(f"updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"total_parts: {len(manifest)}")
    lines.append("---")
    lines.append(f"\n# 🏛️ Hardware Inventory Dashboard: {os.path.basename(root)}")
    lines.append("\n> *This is a Forensic Knowledge Graph of your hardware collection.*")
    
    # Logic for Safety constraints (Simplified for MOC)
    safety_map = {
        "esp32": "⚠️ 3.3V Logic Only",
        "nodemcu": "⚠️ 3.3V Logic Only",
        "raspberry": "🛑 3.3V ONLY - NO 5V",
        "l298n": "⚡ 5V Logic / High Current"
    }

    # Group by Category
    categories = defaultdict(list)
    for filename, data in manifest.items():
        if isinstance(data, list): data = data[0]
        cat = data.get("primary_category", "Uncategorized")
        categories[cat].append((filename, data))

    lines.append("\n## 📊 Inventory by Category\n")
    
    for cat in sorted(categories.keys()):
        lines.append(f"### {cat.replace('_', ' ')} ({len(categories[cat])} items)")
        lines.append("| Part / Model | Technical Specs | Qty | Docs | File |")
        lines.append("| :--- | :--- | :--- | :--- | :--- |")
        
        for filename, data in categories[cat]:
            part = data.get("manufacturer_part_number", "Unknown")
            specs = data.get("technical_specs", "No specs found")
            qty = data.get("quantity_estimate", 1)
            
            # Find matching datasheet
            safe_part = "".join([c if c.isalnum() else "-" for c in part]).lower()
            ds_link = "None"
            if os.path.exists(os.path.join(datasheet_dir, f"{safe_part}.pdf")):
                ds_link = f"[PDF](./10_Atlas/Datasheets/{safe_part}.pdf)"
            elif os.path.exists(os.path.join(datasheet_dir, f"{safe_part}.txt")):
                ds_link = f"[Link](./10_Atlas/Datasheets/{safe_part}.txt)"
            
            # Check for safety tag
            safety_note = ""
            for key, note in safety_map.items():
                if key in part.lower():
                    safety_note = f" <br>*{note}*"
            
            # Find the actual current file path (might be renamed)
            # For simplicity in this script, we'll assume the MOC links to the 20_Cards structure
            # We would normally search for the file, but let's use the semantic names if possible.
            lines.append(f"| **{part}**{safety_note} | {specs} | {qty} | {ds_link} | [[{filename}]] |")
        lines.append("")

    lines.append("\n## 🛠️ Rapid Actions")
    lines.append("- [ ] **Run Safety Audit:** `python scripts/safety_audit.py`")
    lines.append("- [ ] **Procure Missing Datasheets:** `python scripts/datasheet_fetcher.py`")
    lines.append("- [ ] **Generate Project Boilerplate:** `python scripts/code_scaffolder.py`")

    lines.append("\n---\n*Generated by Gemini Forensic Engine*")

    with open(moc_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    
    print(f"✅ High-Intelligence MOC Generated at: {moc_path}")

from collections import defaultdict
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("directory")
    args = parser.parse_args()
    generate_moc(args.directory)
