import { describe, it, expect } from 'vitest';
import {
  exportSpiceNetlist,
  type SpiceExportInput,
  type SpiceExportConfig,
} from '../export/spice-exporter';
import type { CircuitInstanceRow, CircuitNetRow, ComponentPart } from '@shared/schema';

// =============================================================================
// Fixtures — typed to match Drizzle-inferred row shapes
// =============================================================================

function makeInstance(overrides: Partial<CircuitInstanceRow> = {}): CircuitInstanceRow {
  return {
    id: 1,
    circuitId: 1,
    partId: 100,
    subDesignId: null,
    referenceDesignator: 'R1',
    schematicX: 0,
    schematicY: 0,
    schematicRotation: 0,
    breadboardX: null,
    breadboardY: null,
    breadboardRotation: 0,
    pcbX: null,
    pcbY: null,
    pcbRotation: 0,
    pcbSide: 'front',
    properties: {},
    createdAt: new Date(),
    ...overrides,
  };
}

function makeNet(overrides: Partial<CircuitNetRow> = {}): CircuitNetRow {
  return {
    id: 1,
    circuitId: 1,
    name: 'NET1',
    netType: 'signal',
    voltage: null,
    busWidth: null,
    segments: [],
    labels: [],
    style: {},
    createdAt: new Date(),
    ...overrides,
  };
}

function makePart(overrides: Partial<ComponentPart> = {}): ComponentPart {
  return {
    id: 100,
    projectId: 1,
    nodeId: null,
    meta: { family: 'resistor', title: 'Resistor' },
    connectors: [
      { id: 'pin1', name: 'PIN1', connectorType: 'pad', shapeIds: {} },
      { id: 'pin2', name: 'PIN2', connectorType: 'pad', shapeIds: {} },
    ],
    buses: [],
    views: {},
    constraints: [],
    version: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    ...overrides,
  };
}

function makeConfig(overrides: Partial<SpiceExportConfig> = {}): SpiceExportConfig {
  return {
    analysis: 'op',
    ...overrides,
  };
}

function makeInput(overrides: Partial<SpiceExportInput> = {}): SpiceExportInput {
  return {
    circuitName: 'Test Circuit',
    instances: [],
    nets: [],
    parts: [],
    config: makeConfig(),
    ...overrides,
  };
}

// =============================================================================
// Basic output structure
// =============================================================================

describe('exportSpiceNetlist — basic output', () => {
  it('returns netlist, filename, and warnings', () => {
    const output = exportSpiceNetlist(makeInput());

    expect(output).toHaveProperty('netlist');
    expect(output).toHaveProperty('filename');
    expect(output).toHaveProperty('warnings');
    expect(typeof output.netlist).toBe('string');
    expect(typeof output.filename).toBe('string');
    expect(Array.isArray(output.warnings)).toBe(true);
  });

  it('generates a sanitized filename from circuit name', () => {
    const output = exportSpiceNetlist(makeInput({ circuitName: 'My Circuit / Rev 2' }));
    expect(output.filename).toBe('my_circuit___rev_2.cir');
  });

  it('uses default filename for empty circuit name', () => {
    const output = exportSpiceNetlist(makeInput({ circuitName: '' }));
    expect(output.filename).toBe('circuit.cir');
  });

  it('includes title line and generator comment', () => {
    const output = exportSpiceNetlist(makeInput({ circuitName: 'Amplifier' }));
    expect(output.netlist).toContain('* Amplifier');
    expect(output.netlist).toContain('* Generated by ProtoPulse');
  });

  it('includes .END directive', () => {
    const output = exportSpiceNetlist(makeInput());
    expect(output.netlist).toContain('.END');
  });

  it('includes .CONTROL block', () => {
    const output = exportSpiceNetlist(makeInput());
    expect(output.netlist).toContain('.CONTROL');
    expect(output.netlist).toContain('run');
    expect(output.netlist).toContain('.ENDC');
  });
});

// =============================================================================
// Component generation by family
// =============================================================================

describe('exportSpiceNetlist — component families', () => {
  it('generates R line for resistor family', () => {
    const output = exportSpiceNetlist(makeInput({
      instances: [makeInstance({
        id: 1, partId: 100, referenceDesignator: 'R1',
        properties: { value: '10K' },
      })],
      nets: [
        makeNet({ id: 1, name: 'N1', segments: [{ fromInstanceId: 1, fromPin: 'pin1', toInstanceId: 1, toPin: 'pin1' }] }),
        makeNet({ id: 2, name: 'GND', netType: 'ground', segments: [{ fromInstanceId: 1, fromPin: 'pin2', toInstanceId: 1, toPin: 'pin2' }] }),
      ],
      parts: [makePart({ id: 100, meta: { family: 'resistor' } })],
    }));

    expect(output.netlist).toMatch(/R1\s+\d+\s+\d+\s+10K/);
  });

  it('generates C line for capacitor family', () => {
    const output = exportSpiceNetlist(makeInput({
      instances: [makeInstance({
        id: 1, partId: 100, referenceDesignator: 'C1',
        properties: { value: '100n' },
      })],
      nets: [
        makeNet({ id: 1, name: 'N1', segments: [{ fromInstanceId: 1, fromPin: 'pin1', toInstanceId: 1, toPin: 'pin1' }] }),
        makeNet({ id: 2, name: 'GND', netType: 'ground', segments: [{ fromInstanceId: 1, fromPin: 'pin2', toInstanceId: 1, toPin: 'pin2' }] }),
      ],
      parts: [makePart({ id: 100, meta: { family: 'capacitor' } })],
    }));

    expect(output.netlist).toMatch(/C1\s+\d+\s+\d+\s+100n/);
  });

  it('generates L line for inductor family', () => {
    const output = exportSpiceNetlist(makeInput({
      instances: [makeInstance({
        id: 1, partId: 100, referenceDesignator: 'L1',
        properties: { value: '10u' },
      })],
      nets: [
        makeNet({ id: 1, name: 'N1', segments: [{ fromInstanceId: 1, fromPin: 'pin1', toInstanceId: 1, toPin: 'pin1' }] }),
        makeNet({ id: 2, name: 'GND', netType: 'ground', segments: [{ fromInstanceId: 1, fromPin: 'pin2', toInstanceId: 1, toPin: 'pin2' }] }),
      ],
      parts: [makePart({ id: 100, meta: { family: 'inductor' } })],
    }));

    expect(output.netlist).toMatch(/L1\s+\d+\s+\d+\s+10u/);
  });

  it('generates D line with .MODEL for diode family', () => {
    const output = exportSpiceNetlist(makeInput({
      instances: [makeInstance({
        id: 1, partId: 100, referenceDesignator: 'D1',
        properties: {},
      })],
      nets: [
        makeNet({ id: 1, name: 'N1', segments: [{ fromInstanceId: 1, fromPin: 'anode', toInstanceId: 1, toPin: 'anode' }] }),
        makeNet({ id: 2, name: 'GND', netType: 'ground', segments: [{ fromInstanceId: 1, fromPin: 'cathode', toInstanceId: 1, toPin: 'cathode' }] }),
      ],
      parts: [makePart({
        id: 100,
        meta: { family: 'diode' },
        connectors: [
          { id: 'anode', name: 'anode', connectorType: 'pad', shapeIds: {} },
          { id: 'cathode', name: 'cathode', connectorType: 'pad', shapeIds: {} },
        ],
      })],
    }));

    expect(output.netlist).toMatch(/D1\s+/);
    expect(output.netlist).toContain('.MODEL');
    expect(output.netlist).toContain(' D(');
  });

  it('generates Q line with .MODEL for BJT family', () => {
    const output = exportSpiceNetlist(makeInput({
      instances: [makeInstance({
        id: 1, partId: 100, referenceDesignator: 'Q1',
        properties: { type: 'NPN' },
      })],
      nets: [
        makeNet({ id: 1, name: 'N1', segments: [{ fromInstanceId: 1, fromPin: 'collector', toInstanceId: 1, toPin: 'collector' }] }),
        makeNet({ id: 2, name: 'N2', segments: [{ fromInstanceId: 1, fromPin: 'base', toInstanceId: 1, toPin: 'base' }] }),
        makeNet({ id: 3, name: 'GND', netType: 'ground', segments: [{ fromInstanceId: 1, fromPin: 'emitter', toInstanceId: 1, toPin: 'emitter' }] }),
      ],
      parts: [makePart({
        id: 100,
        meta: { family: 'bjt' },
        connectors: [
          { id: 'collector', name: 'collector', connectorType: 'pad', shapeIds: {} },
          { id: 'base', name: 'base', connectorType: 'pad', shapeIds: {} },
          { id: 'emitter', name: 'emitter', connectorType: 'pad', shapeIds: {} },
        ],
      })],
    }));

    expect(output.netlist).toMatch(/Q1\s+/);
    expect(output.netlist).toContain('.MODEL');
    expect(output.netlist).toContain('NPN');
  });

  it('generates V line for voltage source family', () => {
    const output = exportSpiceNetlist(makeInput({
      instances: [makeInstance({
        id: 1, partId: 100, referenceDesignator: 'V1',
        properties: { value: '5' },
      })],
      nets: [
        makeNet({ id: 1, name: 'VCC', segments: [{ fromInstanceId: 1, fromPin: 'positive', toInstanceId: 1, toPin: 'positive' }] }),
        makeNet({ id: 2, name: 'GND', netType: 'ground', segments: [{ fromInstanceId: 1, fromPin: 'negative', toInstanceId: 1, toPin: 'negative' }] }),
      ],
      parts: [makePart({
        id: 100,
        meta: { family: 'voltage source' },
        connectors: [
          { id: 'positive', name: 'positive', connectorType: 'pad', shapeIds: {} },
          { id: 'negative', name: 'negative', connectorType: 'pad', shapeIds: {} },
        ],
      })],
    }));

    expect(output.netlist).toMatch(/V1\s+/);
    expect(output.netlist).toContain('DC 5');
  });

  it('generates generic X subcircuit for unknown families', () => {
    const output = exportSpiceNetlist(makeInput({
      instances: [makeInstance({
        id: 1, partId: 100, referenceDesignator: 'U1',
        properties: {},
      })],
      nets: [],
      parts: [makePart({
        id: 100,
        meta: { family: 'microcontroller' },
        connectors: [
          { id: 'pin1', name: 'VCC', connectorType: 'pad', shapeIds: {} },
          { id: 'pin2', name: 'GND', connectorType: 'pad', shapeIds: {} },
        ],
      })],
    }));

    expect(output.netlist).toMatch(/X/);
    expect(output.netlist).toContain('MICROCONTROLLER');
    expect(output.warnings.length).toBeGreaterThan(0);
    expect(output.warnings[0]).toContain('subcircuit');
  });
});

// =============================================================================
// Node mapping
// =============================================================================

describe('exportSpiceNetlist — node mapping', () => {
  it('assigns node 0 to ground nets', () => {
    const output = exportSpiceNetlist(makeInput({
      nets: [
        makeNet({ id: 1, name: 'GND', netType: 'ground' }),
        makeNet({ id: 2, name: 'VCC', netType: 'power' }),
      ],
    }));

    expect(output.netlist).toContain('0 = GND');
  });

  it('assigns node 0 for common ground net names', () => {
    for (const groundName of ['GND', 'AGND', 'DGND', 'VSS', '0']) {
      const output = exportSpiceNetlist(makeInput({
        nets: [makeNet({ id: 1, name: groundName, netType: 'signal' })],
      }));
      expect(output.netlist).toContain(`0 = ${groundName}`);
    }
  });

  it('warns when no ground net is present', () => {
    const output = exportSpiceNetlist(makeInput({
      instances: [makeInstance({
        id: 1, partId: 100, referenceDesignator: 'R1',
        properties: { value: '1K' },
      })],
      nets: [makeNet({ id: 1, name: 'VCC', netType: 'power' })],
      parts: [makePart({ id: 100 })],
    }));

    expect(output.warnings.some(w => w.toLowerCase().includes('ground'))).toBe(true);
  });
});

// =============================================================================
// Analysis cards
// =============================================================================

describe('exportSpiceNetlist — analysis types', () => {
  it('generates .OP card for operating point analysis', () => {
    const output = exportSpiceNetlist(makeInput({
      config: makeConfig({ analysis: 'op' }),
    }));
    expect(output.netlist).toContain('.OP');
    expect(output.netlist).toContain('print all');
  });

  it('generates .TRAN card for transient analysis', () => {
    const output = exportSpiceNetlist(makeInput({
      config: makeConfig({
        analysis: 'tran',
        transient: { startTime: 0, stopTime: 0.001, timeStep: 0.000001 },
      }),
    }));
    expect(output.netlist).toContain('.TRAN');
    expect(output.netlist).toContain('plot all');
  });

  it('generates .AC card for AC analysis', () => {
    const output = exportSpiceNetlist(makeInput({
      config: makeConfig({
        analysis: 'ac',
        ac: { startFreq: 1, stopFreq: 1000000, numPoints: 100, sweepType: 'dec' },
      }),
    }));
    expect(output.netlist).toContain('.AC DEC');
  });

  it('generates .DC card for DC sweep analysis', () => {
    const output = exportSpiceNetlist(makeInput({
      config: makeConfig({
        analysis: 'dc',
        dcSweep: { sourceName: 'V1', startValue: 0, stopValue: 5, stepValue: 0.1 },
      }),
    }));
    expect(output.netlist).toContain('.DC V1');
  });

  it('includes .TEMP directive for non-default temperature', () => {
    const output = exportSpiceNetlist(makeInput({
      config: makeConfig({ temperature: 85 }),
    }));
    expect(output.netlist).toContain('.TEMP 85');
  });

  it('omits .TEMP for default temperature (27)', () => {
    const output = exportSpiceNetlist(makeInput({
      config: makeConfig({ temperature: 27 }),
    }));
    expect(output.netlist).not.toContain('.TEMP');
  });
});

// =============================================================================
// Edge cases
// =============================================================================

describe('exportSpiceNetlist — edge cases', () => {
  it('handles empty instances list', () => {
    const output = exportSpiceNetlist(makeInput({ instances: [] }));
    expect(output.netlist).toContain('.END');
  });

  it('skips instances with missing parts and adds warning', () => {
    const output = exportSpiceNetlist(makeInput({
      instances: [makeInstance({ id: 1, partId: 999, referenceDesignator: 'U1' })],
      parts: [], // no parts
    }));

    expect(output.netlist).toContain('part not found');
    expect(output.warnings.some(w => w.includes('not found'))).toBe(true);
  });

  it('skips components with no connectors and adds warning', () => {
    const output = exportSpiceNetlist(makeInput({
      instances: [makeInstance({ id: 1, partId: 100, referenceDesignator: 'U1' })],
      parts: [makePart({ id: 100, meta: { family: 'resistor' }, connectors: [] })],
    }));

    expect(output.warnings.some(w => w.includes('no connectors'))).toBe(true);
  });
});
