import { describe, expect, it } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

const repoRoot = resolve(__dirname, "..", "..");
const capabilityPath = resolve(repoRoot, "src-tauri", "capabilities", "default.json");
const permissionsDir = resolve(repoRoot, "src-tauri", "permissions", "autogenerated");

const requiredAppCommandPermissions = [
  "allow-frontend-ready-for-project-open-requests",
  "allow-read-user-setting",
  "allow-write-user-setting",
  "allow-read-kanban-state",
  "allow-write-kanban-state",
  "allow-read-project-design-variables",
  "allow-write-project-design-variables",
  "allow-show-save-dialog",
  "allow-show-open-dialog",
  "allow-read-file",
  "allow-write-file",
  "allow-get-version",
  "allow-get-platform",
];

describe("Tauri app command permissions", () => {
  it("attaches generated app command permissions to the main window capability", () => {
    const capability = JSON.parse(readFileSync(capabilityPath, "utf8")) as {
      windows?: string[];
      permissions?: Array<string | { identifier?: string }>;
    };

    expect(capability.windows).toContain("main");

    const attachedPermissions = new Set(
      (capability.permissions ?? []).map((permission) =>
        typeof permission === "string" ? permission : permission.identifier,
      ),
    );

    for (const permission of requiredAppCommandPermissions) {
      expect(attachedPermissions.has(permission), `${permission} is not attached`).toBe(true);
    }
  });

  it("keeps required app command permission files generated", () => {
    for (const permission of requiredAppCommandPermissions) {
      const command = permission.replace(/^allow-/, "").replaceAll("-", "_");
      const permissionPath = resolve(permissionsDir, `${command}.toml`);
      expect(existsSync(permissionPath), `${permissionPath} is missing`).toBe(true);
    }
  });
});
