// AUTO-GENERATED by script/generate-api-types.ts — do not edit manually
// Run `npm run types:generate` to regenerate

import type {
  Project,
  InsertProject,
  ArchitectureNode,
  InsertArchitectureNode,
  ArchitectureEdge,
  InsertArchitectureEdge,
  BomItem,
  InsertBomItem,
  ValidationIssue,
  InsertValidationIssue,
  ChatMessage,
  InsertChatMessage,
  HistoryItem,
  InsertHistoryItem,
  User,
  InsertUser,
  Session,
  ApiKeyRecord,
  UserChatSettings,
  InsertUserChatSettings,
  ComponentPart,
  InsertComponentPart,
  ComponentLibraryEntry,
  InsertComponentLibrary,
  CircuitDesignRow,
  InsertCircuitDesign,
  CircuitInstanceRow,
  InsertCircuitInstance,
  CircuitNetRow,
  InsertCircuitNet,
  CircuitWireRow,
  InsertCircuitWire,
  CircuitViaRow,
  InsertCircuitVia,
  SimulationResultRow,
  InsertSimulationResult,
  SimulationScenario,
  InsertSimulationScenario,
  ArduinoWorkspace,
  InsertArduinoWorkspace,
  ArduinoBuildProfile,
  InsertArduinoBuildProfile,
  ArduinoJob,
  InsertArduinoJob,
  ArduinoSerialSession,
  InsertArduinoSerialSession,
  ArduinoSketchFile,
  InsertArduinoSketchFile,
  AiActionRow,
  InsertAiAction,
} from './schema';

// ---------------------------------------------------------------------------
// Re-exported entity types
// ---------------------------------------------------------------------------

export type { Project, ArchitectureNode, ArchitectureEdge, BomItem, ValidationIssue, ChatMessage, HistoryItem, User, Session, ApiKeyRecord, UserChatSettings, ComponentPart, ComponentLibraryEntry, CircuitDesignRow, CircuitInstanceRow, CircuitNetRow, CircuitWireRow, CircuitViaRow, SimulationResultRow, SimulationScenario, ArduinoWorkspace, ArduinoBuildProfile, ArduinoJob, ArduinoSerialSession, ArduinoSketchFile, AiActionRow } from './schema';
export type { InsertProject, InsertArchitectureNode, InsertArchitectureEdge, InsertBomItem, InsertValidationIssue, InsertChatMessage, InsertHistoryItem, InsertUser, InsertUserChatSettings, InsertComponentPart, InsertComponentLibrary, InsertCircuitDesign, InsertCircuitInstance, InsertCircuitNet, InsertCircuitWire, InsertCircuitVia, InsertSimulationResult, InsertSimulationScenario, InsertArduinoWorkspace, InsertArduinoBuildProfile, InsertArduinoJob, InsertArduinoSerialSession, InsertArduinoSketchFile, InsertAiAction } from './schema';

// ---------------------------------------------------------------------------
// Patch types — Partial<InsertType> for update/PATCH operations
// ---------------------------------------------------------------------------

export type PatchProject = Partial<InsertProject>;
export type PatchArchitectureNode = Partial<InsertArchitectureNode>;
export type PatchArchitectureEdge = Partial<InsertArchitectureEdge>;
export type PatchBomItem = Partial<InsertBomItem>;
export type PatchValidationIssue = Partial<InsertValidationIssue>;
export type PatchChatMessage = Partial<InsertChatMessage>;
export type PatchHistoryItem = Partial<InsertHistoryItem>;
export type PatchUser = Partial<InsertUser>;
export type PatchUserChatSettings = Partial<InsertUserChatSettings>;
export type PatchComponentPart = Partial<InsertComponentPart>;
export type PatchComponentLibrary = Partial<InsertComponentLibrary>;
export type PatchCircuitDesign = Partial<InsertCircuitDesign>;
export type PatchCircuitInstance = Partial<InsertCircuitInstance>;
export type PatchCircuitNet = Partial<InsertCircuitNet>;
export type PatchCircuitWire = Partial<InsertCircuitWire>;
export type PatchCircuitVia = Partial<InsertCircuitVia>;
export type PatchSimulationResult = Partial<InsertSimulationResult>;
export type PatchSimulationScenario = Partial<InsertSimulationScenario>;
export type PatchArduinoWorkspace = Partial<InsertArduinoWorkspace>;
export type PatchArduinoBuildProfile = Partial<InsertArduinoBuildProfile>;
export type PatchArduinoJob = Partial<InsertArduinoJob>;
export type PatchArduinoSerialSession = Partial<InsertArduinoSerialSession>;
export type PatchArduinoSketchFile = Partial<InsertArduinoSketchFile>;
export type PatchAiAction = Partial<InsertAiAction>;

// ---------------------------------------------------------------------------
// Generic API response wrappers
// ---------------------------------------------------------------------------

export interface ApiResponse<T> {
  data: T;
}

export interface ApiListResponse<T> {
  data: T[];
}

export interface ApiError {
  error: string;
  status: number;
}

export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  pageSize: number;
}

// ---------------------------------------------------------------------------
// Entity-specific response types
// ---------------------------------------------------------------------------

export type ProjectResponse = ApiResponse<Project>;
export type ProjectListResponse = ApiListResponse<Project>;
export type ArchitectureNodeResponse = ApiResponse<ArchitectureNode>;
export type ArchitectureNodeListResponse = ApiListResponse<ArchitectureNode>;
export type ArchitectureEdgeResponse = ApiResponse<ArchitectureEdge>;
export type ArchitectureEdgeListResponse = ApiListResponse<ArchitectureEdge>;
export type BomItemResponse = ApiResponse<BomItem>;
export type BomItemListResponse = ApiListResponse<BomItem>;
export type ValidationIssueResponse = ApiResponse<ValidationIssue>;
export type ValidationIssueListResponse = ApiListResponse<ValidationIssue>;
export type ChatMessageResponse = ApiResponse<ChatMessage>;
export type ChatMessageListResponse = ApiListResponse<ChatMessage>;
export type HistoryItemResponse = ApiResponse<HistoryItem>;
export type HistoryItemListResponse = ApiListResponse<HistoryItem>;
export type UserResponse = ApiResponse<User>;
export type UserListResponse = ApiListResponse<User>;
export type SessionResponse = ApiResponse<Session>;
export type SessionListResponse = ApiListResponse<Session>;
export type ApiKeyResponse = ApiResponse<ApiKeyRecord>;
export type ApiKeyListResponse = ApiListResponse<ApiKeyRecord>;
export type UserChatSettingsResponse = ApiResponse<UserChatSettings>;
export type UserChatSettingsListResponse = ApiListResponse<UserChatSettings>;
export type ComponentPartResponse = ApiResponse<ComponentPart>;
export type ComponentPartListResponse = ApiListResponse<ComponentPart>;
export type ComponentLibraryResponse = ApiResponse<ComponentLibraryEntry>;
export type ComponentLibraryListResponse = ApiListResponse<ComponentLibraryEntry>;
export type CircuitDesignResponse = ApiResponse<CircuitDesignRow>;
export type CircuitDesignListResponse = ApiListResponse<CircuitDesignRow>;
export type CircuitInstanceResponse = ApiResponse<CircuitInstanceRow>;
export type CircuitInstanceListResponse = ApiListResponse<CircuitInstanceRow>;
export type CircuitNetResponse = ApiResponse<CircuitNetRow>;
export type CircuitNetListResponse = ApiListResponse<CircuitNetRow>;
export type CircuitWireResponse = ApiResponse<CircuitWireRow>;
export type CircuitWireListResponse = ApiListResponse<CircuitWireRow>;
export type CircuitViaResponse = ApiResponse<CircuitViaRow>;
export type CircuitViaListResponse = ApiListResponse<CircuitViaRow>;
export type SimulationResultResponse = ApiResponse<SimulationResultRow>;
export type SimulationResultListResponse = ApiListResponse<SimulationResultRow>;
export type SimulationScenarioResponse = ApiResponse<SimulationScenario>;
export type SimulationScenarioListResponse = ApiListResponse<SimulationScenario>;
export type ArduinoWorkspaceResponse = ApiResponse<ArduinoWorkspace>;
export type ArduinoWorkspaceListResponse = ApiListResponse<ArduinoWorkspace>;
export type ArduinoBuildProfileResponse = ApiResponse<ArduinoBuildProfile>;
export type ArduinoBuildProfileListResponse = ApiListResponse<ArduinoBuildProfile>;
export type ArduinoJobResponse = ApiResponse<ArduinoJob>;
export type ArduinoJobListResponse = ApiListResponse<ArduinoJob>;
export type ArduinoSerialSessionResponse = ApiResponse<ArduinoSerialSession>;
export type ArduinoSerialSessionListResponse = ApiListResponse<ArduinoSerialSession>;
export type ArduinoSketchFileResponse = ApiResponse<ArduinoSketchFile>;
export type ArduinoSketchFileListResponse = ApiListResponse<ArduinoSketchFile>;
export type AiActionResponse = ApiResponse<AiActionRow>;
export type AiActionListResponse = ApiListResponse<AiActionRow>;

// ---------------------------------------------------------------------------
// Zod schema re-exports (runtime validators)
// ---------------------------------------------------------------------------

export { insertProjectSchema, insertArchitectureNodeSchema, insertArchitectureEdgeSchema, insertBomItemSchema, insertValidationIssueSchema, insertChatMessageSchema, insertHistoryItemSchema, insertUserSchema, insertUserChatSettingsSchema, insertComponentPartSchema, insertComponentLibrarySchema, insertCircuitDesignSchema, insertCircuitInstanceSchema, insertCircuitNetSchema, insertCircuitWireSchema, insertCircuitViaSchema, insertSimulationResultSchema, insertSimulationScenarioSchema, insertArduinoWorkspaceSchema, insertArduinoBuildProfileSchema, insertArduinoJobSchema, insertArduinoSerialSessionSchema, insertArduinoSketchFileSchema, insertAiActionSchema } from './schema';
