/**
 * 9-bucket localStorage migration planner (Phase 3 Task 3.2 — dry-run,
 * R4 retro Wave 3 rewrite).
 *
 * Reads a snapshot of localStorage entries, classifies each key into one of
 * the migration buckets defined in
 * docs/audits/2026-05-09-tauri-v2-migration-phase1-storage-and-runtime-audit.md,
 * and returns a dry-run plan that names — but does NOT execute — the migration
 * actions per bucket.
 *
 * Classifier source of truth: `storage-key-inventory.json` (generated by
 * `scripts/dev/generate-storage-key-inventory.ts`). The inventory is built
 * from a curated explicit-key map + parameterized patterns over a live rg
 * scan of the codebase. Drift is caught by
 * `scripts/dev/check-storage-key-inventory.ts`.
 *
 * This module performs ZERO mutations. The actual data migration is a
 * separate task that consumes this plan, prompts the user, and writes
 * through to the chosen targets with rollback markers.
 */

import inventoryData from './storage-key-inventory.json';

export type StorageBucket =
  | 'session-auth'
  | 'project-data'
  | 'user-prefs'
  | 'history-cache'
  | 'catalog-shared'
  | 'hardware-presets'
  | 'ux-flags'
  | 'migration-markers'
  | 'event-name-not-storage';

export type MigrationTarget =
  | 'os-keychain'
  | 'native-fs'
  | 'tauri-plugin-store'
  | 'server-with-cache'
  | 'delete-after-migration'
  | 'never-migrate';

interface InventoryEntry {
  key: string;
  classifiedAs: StorageBucket;
  sensitive: boolean;
  callSites: Array<{ file: string; line: number }>;
}

const INVENTORY: ReadonlyArray<InventoryEntry> = inventoryData as InventoryEntry[];

// Build lookup map once at module load. Includes event-name entries
// (they classify as 'event-name-not-storage'); the planner's bucket structure
// keeps event names out of the migration target lists naturally.
const INVENTORY_MAP: ReadonlyMap<string, StorageBucket> = new Map(
  INVENTORY.map((e) => [e.key, e.classifiedAs]),
);

const SENSITIVE_KEYS: ReadonlySet<string> = new Set(
  INVENTORY.filter((e) => e.sensitive).map((e) => e.key),
);

/**
 * Defensive sensitive-key oracle: any key matching this regex MUST classify
 * as session-auth (or NOT classify at all if it's an event name etc.). The
 * generator script also applies this oracle at build time; live classifier
 * applies it as a runtime safeguard.
 */
export const SENSITIVE_KEY_ORACLE =
  /(api[-_:]?keys?|private[-_:]?key|access[-_:]?key|secret|oauth|bearer|credential|token|password|session[-_:]?id$|^sessionId$|jwt|public-api[:_-]?keys|public-api[:_-]?webhooks)/i;

/**
 * Parameterized patterns for runtime-generated key suffixes (project UUIDs,
 * panel IDs, sim IDs). MUST match the generator's PARAMETERIZED list.
 */
const PARAMETERIZED_PATTERNS: ReadonlyArray<{ pattern: RegExp; bucket: StorageBucket }> = [
  { pattern: /^protopulse-panel-layout(:|$)/, bucket: 'project-data' },
  { pattern: /^protopulse:design-variables:project:/, bucket: 'project-data' },
  { pattern: /^protopulse-activity-feed-/, bucket: 'history-cache' },
  { pattern: /^protopulse-component-links-/, bucket: 'project-data' },
  { pattern: /^protopulse:plugin-data:/, bucket: 'project-data' },
  { pattern: /^protopulse-recent-projects(?::|$)/, bucket: 'history-cache' },
  { pattern: /^protopulse-exported-/, bucket: 'project-data' },
  { pattern: /^protopulse:bom-snapshot-cost:/, bucket: 'project-data' },
  { pattern: /^protopulse-order-history(?::|$)/, bucket: 'history-cache' },
];

const MIGRATION_TARGETS: Record<StorageBucket, MigrationTarget> = {
  'session-auth': 'os-keychain',
  'project-data': 'native-fs',
  'user-prefs': 'tauri-plugin-store',
  'history-cache': 'tauri-plugin-store',
  'catalog-shared': 'server-with-cache',
  'hardware-presets': 'tauri-plugin-store',
  'ux-flags': 'tauri-plugin-store',
  'migration-markers': 'delete-after-migration',
  'event-name-not-storage': 'never-migrate',
};

export interface BucketSpec {
  bucket: StorageBucket;
  target: MigrationTarget;
}

/**
 * Bucket metadata for audit/UI consumers + back-compat with the original
 * regex-classifier API surface. Pre-R4-retro this was the source of truth;
 * post-retro the inventory JSON is. This export remains as a stable shape
 * for callers that want to enumerate buckets + their migration targets.
 */
export const STORAGE_BUCKETS: Record<StorageBucket, BucketSpec> = Object.fromEntries(
  (Object.keys(MIGRATION_TARGETS) as StorageBucket[]).map((b) => [
    b,
    { bucket: b, target: MIGRATION_TARGETS[b] },
  ]),
) as Record<StorageBucket, BucketSpec>;

/**
 * Classify a single localStorage key into a bucket. Returns null when no
 * inventory entry and no parameterized pattern matches — caller surfaces
 * these via `plan.unclassified` for human review (often by adding the key
 * to the generator's CURATED map and regenerating).
 */
export function classifyStorageKey(key: string): StorageBucket | null {
  // 1. Inventory exact-match (covers all curated + WINDOW_EVENT_NAMES).
  const direct = INVENTORY_MAP.get(key);
  if (direct) return direct;

  // 2. Parameterized fallback for keys with runtime-generated suffixes.
  for (const { pattern, bucket } of PARAMETERIZED_PATTERNS) {
    if (pattern.test(key)) return bucket;
  }

  // 3. Unknown → null (caller surfaces).
  return null;
}

/**
 * Returns `true` if the key is in the inventory's sensitive set OR matches
 * the defensive SENSITIVE_KEY_ORACLE regex. Tests use this to assert that
 * any sensitive-looking key classifies as session-auth.
 */
export function isSensitiveKey(key: string): boolean {
  return SENSITIVE_KEYS.has(key) || SENSITIVE_KEY_ORACLE.test(key);
}

export interface BucketPlan {
  bucket: StorageBucket;
  target: MigrationTarget;
  keys: string[];
  entryCount: number;
}

export interface MigrationPlan {
  status: 'dry-run';
  totalEntries: number;
  mutationsApplied: 0;
  buckets: Record<StorageBucket, BucketPlan>;
  unclassified: string[];
  generatedAt: string;
}

/**
 * Plan the migration of a localStorage snapshot. No side effects.
 *
 * @param snapshot Map of key → value. Pass `new Map(Object.entries(localStorage))`
 *                 to read live state, or hand-build a Map for tests/fixtures.
 */
export function planStorageMigration(snapshot: ReadonlyMap<string, string>): MigrationPlan {
  const allBuckets: StorageBucket[] = [
    'session-auth',
    'project-data',
    'user-prefs',
    'history-cache',
    'catalog-shared',
    'hardware-presets',
    'ux-flags',
    'migration-markers',
    'event-name-not-storage',
  ];

  const buckets: Record<StorageBucket, BucketPlan> = Object.fromEntries(
    allBuckets.map((b) => [
      b,
      { bucket: b, target: MIGRATION_TARGETS[b], keys: [], entryCount: 0 } as BucketPlan,
    ]),
  ) as Record<StorageBucket, BucketPlan>;

  const unclassified: string[] = [];
  for (const key of Array.from(snapshot.keys()).sort()) {
    const bucket = classifyStorageKey(key);
    if (bucket) {
      buckets[bucket].keys.push(key);
      buckets[bucket].entryCount += 1;
    } else {
      unclassified.push(key);
    }
  }

  return {
    status: 'dry-run',
    totalEntries: snapshot.size,
    mutationsApplied: 0,
    buckets,
    unclassified,
    generatedAt: new Date().toISOString().replace(/\.\d{3}Z$/, 'Z'),
  };
}
